### ISSUE TITLE
System admin cannot manage users/courses in instance management

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1000]
System will get a access denied in http://beta.coursemology.org/admin/instance

Debugged and found that it was because:
https://github.com/Coursemology/coursemology2/blob/master/app/models/components/system/admin/system_admin_ability_component.rb#L14

That line is to prevent  default instance from being deleted or edited, but obviously it also prevents the admin to manage the users in the instance.

**Comment by allenwq** [comment]
I would propose to not use authorisation but manually check in code to prevent default instance from being deleted. 

@lowjoel Any thoughts ?

**Comment by lowjoel** [comment]
cannot [:create, :update, :destroy]?

**Comment by allenwq** [comment]
we check `can?(:manage, @instance)` in instance admin pages, that would won't work ?

**Comment by lowjoel** [comment]
that wouldn't work, yes, gotta find an alternative.

**Comment by allenwq** [comment]
Because no one can edit/delete the default instance, I think it's not an authorisation problem anymore. Instead we should explicitly check for that (maybe in the model level ?) and make sure default instance cannot be deleted by anyone.

**Comment by lowjoel** [comment]
there's no way to check that in the views, in that case

**Comment by allenwq** [comment]
checking wether it's the default instance before showing the delete buttons ?  and add a callback to enforce default instance cannot be deleted at model level.

**Comment by lowjoel** [comment]
that's adding coupling for model logic into the views -- I think the abstraction of using an authorization library should be used still.

**Comment by allenwq** [comment]
View need to know the model to some extent, in this special case I don't think there is a way to avoid the coupling, because this specification need to be write down some where. any suggestions ?

**Comment by lowjoel** [comment]
`cannot :update` and `cannot :destroy` shouldn't affect `show`. You should be able to still use `can?(:edit)`.

**Comment by allenwq** [comment]
I thought `:edit` is an alias of `:update` ? let me check.

**Comment by lowjoel** [comment]
I'm not sure about that, maybe it's different?

**Comment by allenwq** [comment]
I tested, if we say `cannot :update`, `can?(:edit)` will return false too.

Actually even this works I will still prefer to not doing it through authorization ><  I think that's less code too. Maybe I show you the draft code first ?

**Comment by allenwq** [comment]
Come up with a draft implementation:
https://github.com/coursemology-collab/coursemology2/commit/c3ee8f3a84ce5f9b8d16d8b9fd78c89d07a12040

**Comment by lowjoel** [comment]
Actually I have the simplest approach. Make all default instances `ActiveRecord::Core#readonly!`

**Comment by allenwq** [comment]
Okay, that's new to me.  

But I just checked, even we made it read only, we still need to handle the exception like `ActiveRecord::ReadOnlyRecord` when default instance get modified ?

**Comment by lowjoel** [comment]
...combine that with can?

**Comment by allenwq** [comment]
Monkey patch Cancancan to let `can?` return false if the record is readonly ?

**Comment by lowjoel** [comment]
You can use `cannot [:update, :destroy], :all { |a| a.readonly? }` since blocks can now be combined with hashes I think?

**Comment by allenwq** [comment]
but it becomes the initial problem again :-P  I also cannot :manage the instance if it's readonly

**Comment by lowjoel** [comment]
yeah, remove the check for manage. changing the properties of the instance should only require showing the instance.

**Comment by allenwq** [comment]
Hmm, I think it's a bit dangerous if it only requires the show permission actually.

**Comment by lowjoel** [comment]
because the instance users are permissions on the instance user, not on the instance. it is the same for all nested resources.

**Comment by allenwq** [comment]
Okay, that's true, will do that then.
