### ISSUE TITLE
Read/Unread

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1023]
Read unread need to be implemented on following components:

- [x] System/Instance Announcements
- [x] Assessments
- [x] Forums
- [x] Pending Submissions
- [x] Materials

**Comment by weiqingtoh** [comment]
How do we implement read/unread for achievements?

**Comment by allenwq** [comment]
When there is a new achievement created, that one is considered unread ?

**Comment by allenwq** [comment]
Just discussed, agreed that achievement should not have unread, it's more of achieved or not.

**Comment by allenwq** [comment]
All tasks have been done.
