### ISSUE TITLE
System admin cannot create group in a course that he/she is not in

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1040]
When the system admin is not in a course, creating a group throws an error. 

What should be the ideal behaviour in such cases, where the `course_user` of the creator doesn't exist? Set the group owner to the course_owner?

**Comment by weiqingtoh** [comment]
This is related to #1021: 

@lowjoel quick question - if Coursemology Admin creates a group in a course where he/she is not a course_user, who should I set as group manager? There are two opens: 

1. Create a course_user for the Coursemology Admin and set the admin as the group manager, or
2. Set the group manager as the course creator. 

I lean towards option 2 as doing option 1 results in Coursemology Admin having many course_users in many courses. The tradeoff with option 2 is that if the admin goes in to create a group, the course creators will be course group managers (without their knowledge). Does that make sense?

**Comment by lowjoel** [comment]
I think option 2 makes more sense. Someone needs to own the group...

How about groups without managers? Can a manager delete the last manager?

**Comment by weiqingtoh** [comment]
I would probably suggest each group to have 1..n managers; once they are managers they are free to do whatever they like within the group - including deleting other managers (I don't foresee this happening though, if for some reason the group managers disagree they are free to have 2 separate groups). 

Arising from this, I think It would also be good if I add a validation to ensure that each group has at least one group_manager.

**Comment by lowjoel** [comment]
OK. that makes sense.
