### ISSUE TITLE
Remove ruby 2.1? 

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1066]
During a discussion with @allenwq, we realise that rubocop's target ruby version is 2.1 - shifting it up to 2.2 and 2.3 would uncover new violations. Would it be good to remove ruby 2.1? This would probably include the removal of that version from travis CI as well. 

Any thoughts @lowjoel ?

**Comment by lowjoel** [comment]
We can remove Ruby 2.1, since we have 2.3.
