### ISSUE TITLE
Ensure that Reminder emails should only be sent for published assessments

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#108]
One use case for short-lived missions is for practical examinations. The mission is published for the duration of the exam.

v1 sends reminder emails even for assessments which are unpublished. This causes confusion to the students who can't see the test yet but are getting reminders to finish it.

This can be solved by also checking the if an assessment is published when deciding if a reminder should be sent.

**Comment by weiqingtoh** [comment]
Fixed in v1 already, just KIV when we are implementing the published assessments.
