### ISSUE TITLE
Implement concrete activities 

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1080]
Activities should be created after students:
- [x] Attempted assessments
- [x] Earned achievements
- [x] Reached levels
- [x] Created forum topics
- [x] Replied forum posts
- [ ] ~~Voted forum posts~~

This should relate to #613 and #1009

**Comment by allenwq** [comment]
@fonglh @kxmbrian @lowjoel @weiqingtoh These activity types are from V1, should some of them be removed or do we want to add new types of activities ? 

To me the first 3 types are the most important and I will implement them first.

**Comment by weiqingtoh** [comment]
Maybe for first one it is Submitted Assessments rather than Attempted Assessments. Other than that, I agree with the rest. 

When surveys are implemented, there will be 1 more activity type as well I guess?

**Comment by allenwq** [comment]
Thanks @weiqingtoh, I suspect most students will submit the assignment just before deadline, that will flush the activity feed and might not be useful, what do you think ? 

@kxmbrian @fonglh Any comments from teaching side ?

**Comment by fonglh** [comment]
I prefer `Attempted`, as submissions can be seen with the number in the sidebar anyway.

`Attempted` is more useful for getting a general impression of how many people have at least clicked into the assessment.

**Comment by kxmbrian** [comment]
I think Attempted Assessment is quite important for reminding/pressuring students to get started (early) on their assignments.

One other possible item that might add to the buzz for students is to announce when there is a change of leader on the leaderboard or when someone new gets on it.

Possible use cases for files:
- Useful to make it more visible to students when tutorial solutions are released etc.
- Sometimes, staff have to edit instructions or code files for a mission. Two sub-cases:
    - Changes are critical. A staff has to make an announcement to ensure students know about them.
    - Changes are minor, e.g. minor rewording, typo. We don't want to spam announcements for these and visibility is low if we announce in the forum. Maybe more students benefit from the file updates if they appear on the activity feed.

Just making suggestions. Don't think these are high priority.

**Comment by allenwq** [comment]
Thanks @kxmbrian ! In that case let's stick with "attempted" then.  We can further discuss the file activity and implement that in future.

**Comment by weiqingtoh** [comment]
Arising from #1089, think about whether upvoting or downvoting is an activity. The complexity comes when certain actions might trigger a 'unvoting' instead, and how we can handle those ([See discussion here](https://github.com/Coursemology/coursemology2/pull/1089#discussion_r66453189)).

**Comment by allenwq** [comment]
@weiqingtoh Can I close this and discuss the forum vote in anther issue?

**Comment by weiqingtoh** [comment]
Yup let's do that.
