### ISSUE TITLE
[For discussion] Course_User factory to default to approved status

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1094]
I spoke to @allenwq and we felt that writing tests involving the [course_users factory](https://github.com/Coursemology/coursemology2/blob/master/spec/factories/course_users.rb) can be improved; our suggest is to have `course_users` be approved by default, rather than having to provide the `:approved` trait every time we create/build a `course_user`. 

Why we think it will help:
- The current situation requires some implicit knowledge of creating a course_user, so this would definitely reduce errors for new developers. 
- Also, certain factories now do not enforce this: [`experience_points_record`](https://github.com/Coursemology/coursemology2/blob/master/spec/factories/course_experience_points_records.rb), [`course_user_achievement`](https://github.com/Coursemology/coursemology2/blob/master/spec/factories/course_user_achievements.rb). _Technically_, experience points and achievements should only be awarded to confirmed `course_users`. 
- The `course_user` with the 'requested' status is only used for `course_user_invitations`, and in all other foreseeable features, there is no need to create a requested `course_user` by default. 

Hence, we are thinking to have it implemented similar to that of the [`user_emails` factory](https://github.com/Coursemology/coursemology2/blob/master/spec/factories/user_emails.rb), where we can pass in an trait to state that the `course_user` is on a 'requested' status. 

```ruby
### Old
# For approved course_users
create(:course_user, :approved, course: course)
# For non-approved course_users
create(:course_user, course: course)

### New
# For approved course_users
create(:course_user, course: course)
# For non-approved course_users
create(:course_user, :unapproved, course: course)
```

Any thoughts on this @lowjoel?

**Comment by lowjoel** [comment]
I think the problem with making something the default is that it is counterintuitive to "unset" something. I believe the intuition behind factory_girl is for factories to always build the minimally required set of values to get an object in place.

From the perspective of a model with a workflow transition, once a factory has transitioned from a -> b and there's no inverse, with b as the default state, the factory cannot create objects with state a.

**Comment by allenwq** [comment]
Currently despite the course invitation specs, all other places expects an `approved` user. I think factories are meant to make the test more maintainable, but setting a seldom used `:unapproved` default defeats the purpose ( Actually today I spend anther 20+ min for debugging because I forgot to set the :approved state and I believe @weiqingtoh posted this issue is also because of the same thing).

There is a good point from @weiqingtoh from our discussion just now, which is to set the `course_studnet` and `course_staff` approved, and leave the `course_user` as unapproved by default.

@lowjoel What do you think ?

**Comment by lowjoel** [comment]
I'm good with course_student and course_staff as approved, but document that somewhere.,
