### ISSUE TITLE
Enforce that staff group users are group managers

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1095]
To ensure that `groups` and `group_users` are used correctly in the course, any `staff` that is added to a `group` should automatically be a `group_manager`. 

Correspondingly, `students` should automatically be a normal `group_user`. (@allenwq is there a use case for a student to be a `group_manager`?)

Related to #1073.

**Comment by allenwq** [comment]
Currently seems no use for a student to be a group manager. unless we want student to manage groups themselves ?

**Comment by lowjoel** [comment]
These are one of those things I think we would need to try out before deciding if we should do this. We don't have sufficient visibility on what the implications of being a group manager are yet.

**Comment by weiqingtoh** [comment]
This is a duplicate of #1045 - will close this.
