### ISSUE TITLE
[Discussion] Annotation Reply Interface

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1152]
# Decision points
### 1. Whether to have a "Reply" button that adds a post to the end of the thread

<img width="326" alt="screen shot 2016-07-08 at 11 45 24 am" src="https://cloud.githubusercontent.com/assets/6252919/16676824/860ebfbe-4501-11e6-8103-e000ffbba9b5.png">

I don't think there is any big issue to go ahead with this one.

### 2. Whether to allow replying to arbitrary posts in the middle of the thread/tree

Having a tree structure can make discussions harder to read
- User has to hunt for the newest posts. We'll need to be sure to highlight them with color.
- The discussion cannot be read in a linear fashion.
- There is a limit to the number of levels of indentation we can render.

In the context of programming files, one benefit is that each discussion point (e.g. each question / issue / concept) for a topic can have it's own thread and be discussed separately. If the discussion is complex enough, having the tree structure might make the discussion more comprehensible.

Other points to consider:
- Is there any harm leaving the option open? Users will likely use the big "Reply" button most of the time.
- Unlike forum discussions, there are usually only two or three people participating in the discussion, so complexity arising from this is limited.
- If such a complex discussion is required, it might be better for the teacher and student to have a face-to-face discussion instead, if possible.
- Having a linear conversation make the interface consistent with the comments center.
- Submission annotations and comments form the bulk of tutor-student interactions on Coursemology, so much of the discussion of concepts happen here. It is possible for discussions to get sufficiently complex to justify a tree structure.

### 3. If allow [2], whether to display the comments linearly or as a tree.

There will be many complications if we flatten the tree for display, for example, we have to override sorting so that posts are displayed in the right place (new replies should be the first child, not the last child). It will also be confusing to read. Are there any strong arguments to do it?

### 4. If disallow [2], whether the posts should form a chain or be on the same level

If we only allow linear commenting, should the parent of each post be the previous post of the topic or should `parent_id` be left as `nil` (i.e. be a "direct child" of the topic)? Display-wise, they are the same.

Semantically, both intents are possible when the user uses the "Reply" button:
- The commenter might intend to raise a new issue regarding the topic
- The commenter might intend to reply to the last post or one of the other existing posts. (<-- More likely)

It will be simpler to let the `parent_id` be `nil` since we would not have to deal with re-parenting posts (see Item 5) when they are deleted. Are they any other considerations?

### 5. Behavior when a comment is deleted

Right now, all the children of a post are deleted with it. This is probably not the ideal behavior and we'll have to deal with it for each kind of discussion topic at some point.

Some options:
- Re-parent such that a post's children is made its parent's children when it is deleted. If we do this, some context for the re-parented posts will be lost.
- Disallow deletion as suggested by @allenwq for forum posts. Perhaps a variant of this idea is to only allow leaf nodes to be deleted. It is quite possible for a tutor to retract a comment for a previous answer after grading a subsequent answer, so I do not favor this for code annotations.
- Show a "Post Deleted" stub.

=====

In the interest of time, I think we can preserve the tree reply functionality but `display: none` the reply icon in the toolbar and let the big "Reply" generate posts with `parent_id` as `nil`.

After we have pinned down and implemented the new behavior for comment deletion, we can enable the feature.

What do you guys think?

**Comment by kxmbrian** [comment]
As discussed, for point [4], if we enforce a linear conversation from the start, it should not be a problem to leave `parent_id`s as `nil` since we can reconstruct the ancestry based on timestamps. To the user, there should be no noticeable difference based on the current display logic.

Since many early users would be migrants from v1, and the new users would be learning the interface from scratch, it is unlikely that having the linear model will trip users up.

The tentative direction for item [5] is
- When leave node is deleted, destroy the node.
- When non-leave node is deleted, show "Post Deleted" stub.

**Comment by allenwq** [comment]
Annotation is implemented.
