### ISSUE TITLE
Duplicate Mission as Training

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#118]
Missions are used for more formal testing. After the test, there is educational value in allowing students to see all the test cases and try to improve their code.

By allowing missions to be duplicated as trainings with all the test cases public, students can still use the auto grader to verify that their improved solutions are correct.

**Comment by wangqiang1208** [comment]
To me this requirement is a bit weird ><

Why not just let them be able to redo the mission ? Or be able to modify
/run code in answer after grading ?

**Comment by fonglh** [comment]
Does that mean having to unsubmit? Or do you mean duplicating the mission and letting them redo?

This is for use after the actual test, when it's ok to make the evaluation tests public as well. We've had a few cases of students submitting new versions of their code as comments and asking for more feedback.

**Comment by wangqiang1208** [comment]
No need Unsubmit. Just like trainings, now we can redo trainings.

**Comment by fonglh** [comment]
Is this already in v1 or planned for v2?

**Comment by wangqiang1208** [comment]
Trainings already in v1, missions not.

**Comment by fonglh** [comment]
Ok so this feature will be implemented by allowing students to redo missions.

Or more generally to redo assessments.

**Comment by wangqiang1208** [comment]
yeah, maybe redo assessment
