### ISSUE TITLE
Refactor Course Homepage 

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1180]
Arising from [this conversation](https://github.com/Coursemology/coursemology2/pull/1166/files/ba3a3048327a9809e94ee00a97b6bc8cc5173f77#r71964170). Idea is to factor out to partials depending on course_user's registered status.

**Comment by ekowidianto** [comment]
Page ported to react in https://github.com/Coursemology/coursemology2/pull/4725
