### ISSUE TITLE
Support python 3.5

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1187]

**Comment by fonglh** [comment]
Depends on https://github.com/Coursemology/polyglot/pull/16

**Comment by fonglh** [comment]
Needs Python 3.5 Docker image which depends on https://github.com/Coursemology/evaluator-images/pull/2

**Comment by fonglh** [comment]
Fixed by the above 2 dependencies. Updated polyglot gem manually on evaluator VM.

Python 3.5 can now be selected as an option and the image gets pulled.
