### ISSUE TITLE
Get test cases without requiring a syntax correct template

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1199]
Use a solution file or other proper ways.

**Comment by fonglh** [comment]
A blank template can be used. Tests do not have to pass on question import so functions can be undefined or have the wrong number of arguments.

Keeping the question import flow and the evaluation flow the same was a key design consideration to ensure consistency in evaluation.

Using environment variables to switch between paths might allow students to bypass proper evaluation by setting the env var in their own code.
