### ISSUE TITLE
Updating time/memory limits alone when package has failed to import does not work

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1204]
## Steps to Reproduce
1. Set a low time and memory limit. e.g. 1 MB and 1 second
2. Upload a package. The error `The package could not be imported: the package exceeded the maximum time allowed by the question.` is shown.
3. Change the memory limit to 30 MB and click 'Update Programming'. The same error message is shown.

However, with the same limits of 30 MB and 1 second, when the same package file is selected for upload before clicking 'Update Programming', it is successfully imported.

**Comment by lowjoel** [comment]
This is probably a display issue more than anything else. What’s happening is that the import failed, and updating the time and memory limit does not trigger another import. Because the import has still failed after changing the time limits, the message is still there. The imports are not reattempted.

**Comment by fonglh** [comment]
If an import has not succeeded before, should it be automatically reattempted when the time/memory limits change?

**Comment by lowjoel** [comment]
No, because in that circumstance we discard the package. Because otherwise it is possible to create answers which use a broken template.

**Comment by fonglh** [comment]
Ok I can see how that might happen. Then the UI shouldn't show the old filename beside the upload button as that seems to imply that the package is still associated with the question.

**Comment by fonglh** [comment]
Edit the UI so the link beside the "Choose File" button doesn't appear when the import fails and the package has been discarded.

Also check that the package really was discarded.
