### ISSUE TITLE
Show stdout/stderr when autograded student code has syntax errors

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1236]
The programming import service checks for errors and returns the stdout and stderr if there are any.

The programming auto grading service should do the same thing. Right now it goes through the workflow with a nil test report, so the student doesn't see anything happening.

**Comment by fonglh** [comment]
Displaying stdout and stderr to students allows test cases to be compromised. Indicate that an error has occurred but don't show additional output.

**Comment by ssyberg** [comment]
Agreed test cases can be compromised, but is there a middle ground solution that gives student some feedback?

**Comment by benleong** [comment]
@fonglh Maybe we can add a flag that will allow the instructor to allow the stdout/stderr to be shown to the students?

**Comment by ssyberg** [comment]
I'd definitely be in to that.. or something that allowed us to return an error message from our testing suite. Either/both.
