### ISSUE TITLE
Find a better method to ensure that radio button for a selected option is checked.

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1241]
Improves #1238 

Ideally, we should not be patching the MCQ instance using `override_option_ids_method_for_form_display!` in the view. 

@allenwq suggested seeing if something like the following is feasible instead:

```
= f.association question.mulitple_choice? ? :option : :options
```

**Comment by jeremyyap** [comment]
I think this is no longer relevant after the React rewrite of submission edit page #2354

Can't find any invocations of `override_option_ids_method_for_form_display!` in the code, think it can be removed.

**Comment by jeremyyap** [comment]
#2493
