### ISSUE TITLE
Links in emails should go to the instance where user is in

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1247]

**Comment by fonglh** [comment]
Duplicate of #1349. Closing this one as #1349 already has some other activity and references.

**Comment by allenwq** [comment]
@fonglh This is not really a duplicate, the confirmation email is generated by devise. 

#1349 is the email in the course with our own template, sorry I should describe clear. will reopen this.

**Comment by allenwq** [comment]
I realised that this is also urgent, links in all email templates need to go to the instance that the course belongs to.

@fonglh Do you want to work on this ?  need to be fixed before users in other instances start using the system

**Comment by allenwq** [comment]
Invitations emails fixed in #1839 

Pending to fix other emails

**Comment by fonglh** [comment]
The notifiers in `app/views/notifiers/course/*` already use the instance host.

**Comment by allenwq** [comment]
👍
