### ISSUE TITLE
Forgetting to switch back to rich text mode clears the content

### ISSUE THREAD

**Issue by evansb** [Coursemology/coursemology2#1250]
To reproduce:
1. Create new assessment
2. Edit the description using HTML mode. Don't put any DOM, just plain text.
3. It should be a valid HTML too, but the update is rejected, when Update Assessment is clicked the change is not reflected

**Comment by evansb** [comment]
Update:

Apparently this seems to be a client side /improper use of `summernote` issue.
If you go back to rich text mode after editing the HTML mode, it will work. However if you didn't go back to rich text mode, the description will reset to `<p><br /></p>`

**Comment by kxmbrian** [comment]
No longer an issue after the React rewrite.
