### ISSUE TITLE
Cannot set user to phantom?

### ISSUE THREAD

**Issue by evansb** [Coursemology/coursemology2#1252]
To reproduce:
Go to students page, tick the Phantom checkbox, and click save. Nothing happened. Tested both locally and on staging server

**Comment by fonglh** [comment]
Turbolinks is giving some problems. Refresh the page and try again.

**Comment by fonglh** [comment]
See #602

**Comment by allenwq** [comment]
What browser are you using ?

**Comment by evansb** [comment]
Chrome. I tried again in Safari and it works.

**Comment by evansb** [comment]
Okay refreshing Chrome works.

Afaik this is not the only page that has Turbolinks issue.
My assessment page, which needs to load the game engine from a CDN, sometimes the game code isn't loaded. Refreshing will make it work again.

Ditto for edit answer page.

Should I recommend student to use FF instead?

**Comment by allenwq** [comment]
I think FF even worse.. it does not have the issue on your side ?

**Comment by evansb** [comment]
Oh yeah, doesn't work on FF as well.

**Comment by benleong** [comment]
@allenwq Why are we using Turbolinks? Can we replace it?

**Comment by allenwq** [comment]
Turbolinks makes page load faster on client side, think this is fixable, just that I was dealing with other things.

**Comment by kxmbrian** [comment]
Forms are not allowed to straddle multiple table cells. This leads to different behaviors depending on the browser used. `<form>`s (or `<div>`s etc) should either be contained within a table cell or should contain the whole table.
