### ISSUE TITLE
Grader and Graded at is set even though submission is not graded.

### ISSUE THREAD

**Issue by evansb** [Coursemology/coursemology2#1266]
Sorry can't show you step to reproduce, but basically this happens to one of our students.
His status is 'submitted' but the grader is set to System and the Graded At is set to submission time + 1 minute.

**Comment by fonglh** [comment]
If this hasn't been fixed yet after the latest round of exp fixes, PM us the student name and submission number.

**Comment by allenwq** [comment]
The submission are pre graded before TA comes, it's normal just the UI is a bit confusing, students won't get any exp.

**Comment by kxmbrian** [comment]
Grader should be set to the TA if not autograded.

**Comment by kxmbrian** [comment]
Related to #1286

**Comment by allenwq** [comment]
Fixed

**Comment by fonglh** [comment]
See #1338.
