### ISSUE TITLE
Change expected field (and maybe expression too) to text type

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1273]
Test cases cannot be imported and fail silently if the meta values don't fit into the database columns.

Update the database column types to `text` instead of `varchar`. However, there might be UI display problems.

@allenwq @kxmbrian what do you all think?

**Comment by allenwq** [comment]
Is that because some validation ? Why cannot be saved ?

**Comment by fonglh** [comment]
It's probably database validation.

**Comment by allenwq** [comment]
I suspect it's AR validation, you can fix the validation instead ?

**Comment by fonglh** [comment]
So it should truncate the data?

**Comment by allenwq** [comment]
The error is because data is too long ?

**Comment by fonglh** [comment]
Yes that's what was discovered by experimentation.

**Comment by benleong** [comment]
What's this about?
