### ISSUE TITLE
Prevent multiple submissions

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1295]
Currently multiple clicks of "attempt" will result in multiple submissions, this should not be allowed. 

At any time, students should only have one active submission.

**Comment by benleong** [comment]
@allenwq How did this happen?

**Comment by fonglh** [comment]
@benleong This was meant to be a feature to allow students to try assessments again multiple times, allowing them extra practice for trainings.

We've since decided on an alternate implementation which I'll be working on. The database has been cleaned of multiple submissions.

**Comment by benleong** [comment]
@fonglh We just support one submission for now.

**Comment by fonglh** [comment]
Yes that's what we'll be doing.

**Comment by fonglh** [comment]
Fixed by #1302.
