### ISSUE TITLE
Directly reattempt the question after answer grading 

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1297]
This will prevent the answers in attempting state generated after finalising in some edge cases.

**Comment by kxmbrian** [comment]
Quick fix: Show "Finalize" button only if answer is Attempting state.

**Comment by fonglh** [comment]
So the problem here is that new answers in the `attempting` state are sometimes created after the submission is finalised?

**Comment by allenwq** [comment]
@fonglh Yes.

**Comment by fonglh** [comment]
Isn't that what we want? Another answer after finalising.

**Comment by allenwq** [comment]
The latest answers all must be in attempting state before finalising.
