### ISSUE TITLE
Edit/Delete button for assessment attachment is only visible to uploader.

### ISSUE THREAD

**Issue by evansb** [Coursemology/coursemology2#1306]
To reproduce:

1. Login as staff
2. Create assessment
3. Upload a file
4. Login as another staff
5. Go to the assessment directory in materials.
6. No edit/delete button is visible.

Is this by design?

**Comment by allenwq** [comment]
This is by design, actually even the uploader should not see it. you are supposed to delete materials in the assessment page ( haven't implemented ), things in the materials are just links.

**Comment by evansb** [comment]
Allright, thanks for clarifying
