### ISSUE TITLE
Improve error message when multiple submissions are created

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1314]
When multiple submissions are created, the error message is `Could not create submission: Creator has already been taken, Creator has already been taken, Assessment has already been taken, Assessment has already been taken, Actable creator has already been taken, and Actable assessment has already been taken`.

Rewrite it with something more readable.

**Comment by weiqingtoh** [comment]
You can probably use validations - http://guides.rubyonrails.org/active_record_validations.html#uniqueness

**Comment by allenwq** [comment]
Also need to remove the default validation generated by schema_validation.
