### ISSUE TITLE
Route submissions sidebar to pending submissions for course_staff

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1318]
Currently clicking `Submissions` in the sidebar routes to the all submissions page, and this was designed mainly for students (so they can check their own submissions. 

For course staff, it might make more sense to directly go to pending submissions instead, since they want to grade. 

No issues right? @allenwq @fonglh @kxmbrian

**Comment by fonglh** [comment]
It's mainly a matter of fixing which tab it links to?

**Comment by allenwq** [comment]
Yah, go ahead.
