### ISSUE TITLE
Add profile picture to each forum post

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1357]

**Comment by cysjonathan** [comment]
I believe this has already been fixed
![selection_015](https://cloud.githubusercontent.com/assets/10083037/18231264/9f639df4-72e7-11e6-8eed-54be7cc36612.png)

**Comment by fonglh** [comment]
@cysjonathan could you reference the PR number which fixed this then close this issue? Thanks!

**Comment by cysjonathan** [comment]
@weiqingtoh If no longer an issue then we can close this, see #1008 **Forum improvements** _Show user profile pictures in topics_

**Comment by allenwq** [comment]
Think @weiqingtoh means the discussion posts, but we also implemented that. Let's close this then.
