### ISSUE TITLE
Multiple comment boxes when going 'back' in the browser

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1374]
Steps to reproduce: 
1. Go to pending comments 
2. Click on any submission
3. Go back to pending comments
4. Now each discussion topic has 2 text boxes. 

Browser: Chrome Version 52.0.2743.116

**Comment by allenwq** [comment]
Did some investigation, related to https://github.com/Coursemology/coursemology2/blob/master/app/assets/javascripts/layout.js#L30
