### ISSUE TITLE
Show actual result of test case evaluation

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1387]
With the unittest framework, a test case passes or fails depending on the result of the assert statements. The actual value of the function under test is not passed back to the app server.

To support this, another key can be added to the meta dictionary, similar to how information is passed back to show the test expression and expected value of the test.

The programming evaluation service will need to be updated to extract and store this new value with the test case results.

**Comment by benleong** [comment]
On Sun, Aug 28, 2016 at 1:38 AM, fonglh <notifications@github.com> wrote:

> With the unittest framework, a test case passes or fails depending on the
> result of the assert statements. The actual value of the function under
> test is not passed back to the app server.
>
> To support this, another key can be added to the meta dictionary, similar
> to how information is passed back to show the test expression and expected
> value of the test.
>
> The programming evaluation service will need to be updated to extract and
> store this new value with the test case results.
>
Let's do this later. Thanks!

- Ben

**Comment by fonglh** [comment]
Covered by #1463 (fixed in #1469) and #1499.
