### ISSUE TITLE
Dropdown does not work in mobile

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1394]
Basically the dropdown menu on the navbar does not work for mobile devices. To reproduce, use a mobile phone, go to navbar, from the dropdown list, try to open 'My Courses'. Button does not get triggered. 

I read about a boostrap fix but need to double check before we fix it -> https://github.com/twbs/bootstrap/issues/7968 

On iPhone 6, tried on Chrome and Safari. Bug was existent in both.

**Comment by allenwq** [comment]
No issue on android chrome.
