### ISSUE TITLE
Date/time event spacing in Latest Activity section

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1399]
Move date/time line closer to the activity it's referring to instead of having an even spacing between the timestamp and the activity description.

**Comment by allenwq** [comment]
@cysjonathan Have you fixed this in #1412  ?

**Comment by cysjonathan** [comment]
Yes I made it have **no** vertical spacing between the Date/Time.

**Comment by allenwq** [comment]
Thanks, but next time you should assign the issue to yourself before working on it, I think @caramelcat is also working on this.

**Comment by cysjonathan** [comment]
Ah my bad. Sorry will go read up how to assign myself things on github

**Comment by allenwq** [comment]
It's OK. Or just post a comment, I think you cannot assign cause you are not in our github team yet.

**Comment by fonglh** [comment]
Also use the fixes/closes syntax so the issues will auto close when the PR is merged.
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by fonglh** [comment]
Fixed in #1412.
