### ISSUE TITLE
Autofill EXP when mission submissions are graded

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1415]
The grading is filled in, but no experience points are awarded

**Comment by fonglh** [comment]
I think this can be done when the autograder assigns the grade, rather than using JS on the page load.

**Comment by allenwq** [comment]
We already have front end code dealing with this, should just extend it.  I have thought about doing it in the backend, but if later grader changes the grade in the page, we still need front end code to adjust the EXP.
