### ISSUE TITLE
Auto graded submissions still appears in pending submissions ( for a while)

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1421]
This confuses the tutors, and they might go and grade them.

**Comment by fonglh** [comment]
So these should be filtered out first?

**Comment by allenwq** [comment]
When we can guarantee no job will fail, then we can filter out them. Now trainings auto grading could also fail due to timeouts.

**Comment by weiqingtoh** [comment]
Since we had defined guided and worksheet more clearly, should we just modify pending submissions to include submissions for worksheet/exam assessments? @allenwq

**Comment by allenwq** [comment]
Yes, agree 👍
