### ISSUE TITLE
Specifying no time limit actually passes 0 to the evaluator

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1438]
`ulimit -t0` results in a CPU time limit of 1 second being set.

This ends up causing some tests to get killed when they shouldn't.

**Comment by fonglh** [comment]
Hardcode a maximum of 90 seconds to prevent DOS on the evaluators from infinite loops and poor code.

**Comment by benleong** [comment]
What do you mean by hardcode? you mean it defaults to 90s if not specified?
