### ISSUE TITLE
Forum thread not deleted when empty

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#1457]
https://beta.coursemology.org/courses/2/forums/trainings/topics/card-magician-question-on-the-function-card_magician
![selection_025](https://cloud.githubusercontent.com/assets/10083037/18324929/8223d858-7571-11e6-9158-13cdc8265b2f.png)

**Comment by weiqingtoh** [comment]
@luoyanjie waiting to confirm if (i) don't show delete button on first post, or (ii) delete button on first post deletes the entire thread.

**Comment by luoyanjie** [comment]
Let me think through the whole forum thingy, propose to the PO and then can make a good decision about this.
