### ISSUE TITLE
Allow graded submissions to be autograded again

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1478]
As grading for an assessment progresses, new test cases could be found. The instructors would then add the new test case into the package, but they would also like to rerun the new test case on already graded submissions.

The autograde button should be made available for graded submissions without affecting published grades.

**Comment by allenwq** [comment]
@fonglh will #2566 fix this as well?

**Comment by fonglh** [comment]
Just verified that the autograder does run again for graded submissions.

#3114 probably helped too.
