### ISSUE TITLE
Submissions have auto gradings but no test results

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1479]
Some submissions are in the graded state, and `latest_answers` have an associated `auto_grading`, but even though the stored job status shows that it completed and there are no errors, there are no `test_results`.

Thus the TA cannot see the pass/fail checkmark on the submission grading page.

**Comment by allenwq** [comment]
I suspect this is because user deleted the package and reuploaded after students submitted. Because after a package is reimported, the test cases and test results of the old question are all deleted.

**Comment by fonglh** [comment]
Possibly related to #1382.

**Comment by luoyanjie** [comment]
Put on hold for further review
