### ISSUE TITLE
Skills in Course user profile page

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1483]
To implement the skills page for course_use profile page (see v1).

This will provide an indication of the mastery level of the course_user (in different aspects) for a particular course.

**Comment by RAGFred** [comment]
This would be a fantastic feature. It would really help me identify my students strengths/weaknesses.

**Comment by trangmei** [comment]
Issue resolved by https://github.com/Coursemology/coursemology2/pull/2969.
