### ISSUE TITLE
When replying to a comment in comments summary, comment indentation is one level too high

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1485]

**Comment by jeremyyap** [comment]
Can't seem to find any examples of this

**Comment by fonglh** [comment]
This was created in response to an email complaint with no other information.

Perhaps it was fixed when the reply nesting was flattened in the view. Another possibility is that the user expected his reply to be indented by 1 level, which is not the case for a straight line of replies.

Let's close this first unless more detail surfaces.
