### ISSUE TITLE
Scribing Feature

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1494]
Allow users to upload PDFs and make annotations on them.

**Comment by fonglh** [comment]
twanngg 🎯 

Create a new question type. For this type of question, uploaded PDFs will be displayed in the browser window directly.

Students will be able to draw directly on the PDF displayed, in various colours and line widths.
Instructors will be able to view student scribblings and add on their own.

**Comment by nicholette** [comment]
👌 😂

**Comment by kxmbrian** [comment]
This feature was made available to users in #2537.
