### ISSUE TITLE
Speed up lesson plan page

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1496]
The slowness of the lesson plan is partly because of the collapse animation.  Need to find a way to speed up this. 

@kxmbrian Any thoughts ?

**Comment by kxmbrian** [comment]
I don't think it contributes to user's perceived sense of slowness. Doesn't the javascript for the animation only kick in after the page is loaded and the content is visible?

**Comment by allenwq** [comment]
Frontend of lesson plan is much faster after React is introduced, will close this.
