### ISSUE TITLE
Award exp by submission time

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1509]
Exp is currently awarded by grading time. A student who submits his answer at the very last minute might not get the full bonus he deserves as the system could only pick it up for grading a minute or so later.

It should be awarded by submission time instead.

**Comment by weiqingtoh** [comment]
Actually the when viewing the code, exp is calculated using the submission time. 

However, there was a case where:
 - assessment was autograded
 - submission was submitted 1 min before `bonus_end_time`
 - submission was graded 1 min after 'bonus_end_time`
 - submission's exp did not receive the `time_bonus_exp`

To try to reproduce this case and figure out what is happening.

**Comment by fonglh** [comment]
I'll help you setup the evaluator locally tomorrow, then you can control the grading delay (within 5 minutes).

**Comment by weiqingtoh** [comment]
Might be good to learn how to setup the evaluator 👍  - but actually we can just use MCQ/MRQ which has a local auto-grading service.

**Comment by fonglh** [comment]
How can you make make it grade just after `bonus_end_time`?

**Comment by weiqingtoh** [comment]
If I'm not wrong, we can grade but not publish the submission, so that will mean all answers have been evaluated but no exp is awarded. Then we manually set the `submitted_at` and `bonus_end_time`, then publish the submission.

**Comment by weiqingtoh** [comment]
This is actually a non issue. Currently exp is calculated based on `submitted_at` timing. To close this.
