### ISSUE TITLE
Use JavaScript to sort workbin files

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1534]
Allow the files in the workbin to be sorted by name or modified time by clicking on the header.

**Comment by hongshaoyang** [comment]
+1.

Would be nice to make the headers (circled below) clickable to sort ascending or descending.

![image](https://user-images.githubusercontent.com/19281800/39697764-ae149628-5224-11e8-9073-ed4f9b6bc446.png)

**Comment by weiqingtoh** [comment]
Related to #2941. Suggestion is to move workbin to a react page, then we do the necessary features there.

**Comment by ekowidianto** [comment]
Moved to react page in https://github.com/Coursemology/coursemology2/pull/4868
