### ISSUE TITLE
Show MCQ/MRQ options on show assessment page

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1546]
For MCQ/MRQ questions on the show assessment page (staff-facing), v1 shows the question and options while v2 currently only shows the question.

Does showing the options help staff, or add to the clutter?

**Comment by weiqingtoh** [comment]
Showing question and options makes sense. We can find a way to not make it too cluttered, I don't think it's impossible.

**Comment by weiqingtoh** [comment]
@luoyanjie would this be something useful for `course_staff` ?

**Comment by weiqingtoh** [comment]
A solution to this is to have the options in a collapsed element by default, and should staff wish to see it, they are able to.

**Comment by trangmei** [comment]
blocked by #3024
