### ISSUE TITLE
Add a column to assessment view to show if it's in worksheet or guided mode

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1553]
To help staff check that they've selected the correct assessment type.

This column should probably only be shown to staff.

**Comment by fonglh** [comment]
Any visual indicator is fine. So small text or another icon beside the title is also fine.

**Comment by weiqingtoh** [comment]
I think we probably need to explain what is `guided` vs `worksheet` as well. Shouldn't be too hard. Maybe an icon + tooltip would suffice (or a similar alternative).

**Comment by allenwq** [comment]
@fonglh @weiqingtoh Since we removed modes, think this can be closed ?
