### ISSUE TITLE
Create seed data for development

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1562]
Enhance `db/seeds/development.rb` to add some useful data for local testing.
- [ ] Create a course
- [ ] Create some test users and assign them to the course
- [ ] Create an assessment and some questions
- [ ] Any other useful data

**Comment by fonglh** [comment]
@chesterhow @ivantjh come contribute towards your free t-shirt!

**Comment by zachariast** [comment]
@fonglh Can i contribute on that?

**Comment by fonglh** [comment]
@zachariast sure!

**Comment by amingilani** [comment]
@zachariast beat you to it! 😁
