### ISSUE TITLE
Newly added Facebook like button conflicts with EFF Privacy Badger plugin

### ISSUE THREAD

**Issue by caramelcat** [Coursemology/coursemology2#1567]
![privacy_badger](https://cloud.githubusercontent.com/assets/8869365/19098061/a28922d0-8adc-11e6-85d5-230e6039f960.png)

**Top:** expected result
**Botton:** button replaced by EFF Privacy Badger plugin on Chrome (only affects paranoid users who use such a plugin). The replacement is not aligned correctly.

https://www.eff.org/privacybadger

**Comment by fonglh** [comment]
This is obscure.

References #1542, references https://github.com/Coursemology/coursemology-theme/pull/5

**Comment by weiqingtoh** [comment]
Definitely obscure, but we need to figure out whether this is something we need to fix on privacybadger's side or on coursemology's side.

**Comment by weiqingtoh** [comment]
Solved by https://github.com/Coursemology/coursemology-theme/pull/7
