### ISSUE TITLE
React-rails integration

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1569]
To prepare for #1568

Using react will help to decouple the frontend from the backend. This will be helpful for the shift to a Phoenix backend.

**Comment by kxmbrian** [comment]
@justwudi We are thinking of using [react_on_rails](https://github.com/shakacode/react_on_rails). Do you have any thoughts on this choice?

**Comment by justwudi** [comment]
👍

**Comment by allenwq** [comment]
Fixed by @kxmbrian in #1608
