### ISSUE TITLE
Create maintenance page

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1576]
Create a file `public/504.html` with a self contained maintenance page. This will be copied to nginx for use when the rails servers are down.

Best to be in the same style as https://github.com/Coursemology/coursemology-theme/

Using the theme above, the homepage looks like the screenshot below.

![screen shot 2016-10-07 at 11 09 17 am](https://cloud.githubusercontent.com/assets/1902527/19177753/84195830-8c7e-11e6-8f49-37cb2df61165.png)

**Comment by logeshmallow** [comment]
@fonglh Can I work on this and send you a pull request?

**Comment by fonglh** [comment]
Sure!

**Comment by logeshmallow** [comment]
@fonglh Thanks, I will work on this and send you the pull request soon.

**Comment by logeshmallow** [comment]
@fonglh I have sent a pull request. Please have a look into it.
![screen shot 2016-10-12 at 12 21 07 pm](https://cloud.githubusercontent.com/assets/4848568/19300324/51917030-9077-11e6-8b6a-c9f0455b2285.png)
