### ISSUE TITLE
Achievement show page should display phantom users

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1584]
Phantom users can be awarded achievements too. Show them as well in a separate section.

References #1582, references #1583.

**Comment by weiqingtoh** [comment]
Not sure if we need this actually, cause the achievement show page is public. So phantom users should not be shown to students.

**Comment by fonglh** [comment]
Yup students shouldn't see phantom users, but not doing this means that the achievement award page is inconsistent with the show page.

**Comment by weiqingtoh** [comment]
My sensing on this is that this is useful only if course teaching staff need to track who has or has not been awarded - in that case, we can show an additional section to staff - phantom users who has obtained this achievement. Honestly it is not a compelling reason for me.
