### ISSUE TITLE
Attempting password protected exam assessment returns a JSON response.

### ISSUE THREAD

**Issue by evansb** [Coursemology/coursemology2#1610]
For some reason, after inputting the correct password as student I get this
[Screenshot](https://www.dropbox.com/s/2pzapctedjli1gk/Screenshot%202016-10-24%2023.17.36.png?dl=0).

**Comment by allenwq** [comment]
What browser are you using ? have you enabled javascript ?

**Comment by evansb** [comment]
Chrome Version 56.0.2899.0 canary (64-bit), yes Javascript is enabled

**Comment by allenwq** [comment]
Looks like the javascript handler on source academy side is not called when clicking the button.  I suspect source academy's CSS classes are different from our main site.

**Comment by allenwq** [comment]
Just checked the CSS, they are same, it's rather the listener not be called. 

Our main site has no problem,  the js code handles this is here: https://github.com/Coursemology/coursemology2/blob/master/app/assets/javascripts/course/assessment/sessions.js#L39

Have you installed any other js libraries in the theme, possible there're some conflicts ?

**Comment by allenwq** [comment]
I think this issue is related to codeacademy theme.  @evansb Any updates from your side ? otherwise I will close this.

**Comment by evansb** [comment]
Yes, just close it for now
