### ISSUE TITLE
Rename question weight field

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1611]
Change display title of the field to `Order`. This is a temporary fix in response to user feedback.

It will be superseded by drag and drop reordering, hiding the `Weight` field from the end user.

**Comment by weiqingtoh** [comment]
@fonglh can we add the drag and drop as a separate issue or just change this to do that instead? Otherwise it will get forgotten.

**Comment by fonglh** [comment]
Created as #1613.
