### ISSUE TITLE
Staff cannot see private test cases of submissions in 'attempting' state

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1617]
https://github.com/Coursemology/coursemology2/blob/master/app/views/course/assessment/answer/programming/_test_cases.html.slim#L2 uses the 'cancancan' gem to check for the ability to `:grade` an answer.

The ability is defined in https://github.com/Coursemology/coursemology2/blob/master/app/models/course/assessment/assessment_ability.rb#L103 and only allows them to grade submissions which are not being attempted.

This means staff cannot view private/evaluation tests when testing missions or when helping students which are stuck on trainings.

Either relax the `:grade` ability or create a new ability for viewing test cases.

**Comment by allenwq** [comment]
If relax `:grade` need to check all the places where `can? :grade` is used (e.g. make sure buttons for grading are displayed correctly, etc) 

Alternatively we can use `can?(:manage, @assessment)` instead.

**Comment by weiqingtoh** [comment]
The other way is to replace the variable `is_grader` to `can?(:read, @submission) && current_course_user.staff?`.

Like Wang Qiang mentioned, relaxing grade might not be the best option as that is used to restrict state transitions. 

The other suggestion is fine (create new ability). :+1:
