### ISSUE TITLE
Missing relations when running rake db:schema:load

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#162]
`rake db:schema:load` complains about missing relations. However, `rake db:setup` works fine.

@allenwq suspects that the issue might be due to the schema_plus gem

**Comment by lowjoel** [comment]
@fonglh Can you check if this has been fixed in master? I think upgrading schema_plus should have fixed it.

**Comment by allenwq** [comment]
We still cannot do schema:load, it was because https://github.com/SchemaPlus/schema_plus/issues/155

**Comment by lowjoel** [comment]
@weiqingtoh is this fixed?

**Comment by allenwq** [comment]
Fixed, it's a quite old issue with schema_plus
