### ISSUE TITLE
Implement email settings

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1688]
- [ ] Allow the user to turn on/off emails ( reminder, announcements, etc ).
- [ ] Allow the customization of when to send the reminder email, default is 24 hours before the deadline.

**Comment by fonglh** [comment]
See sample from v1

![screen shot 2017-01-16 at 3 41 24 pm](https://cloud.githubusercontent.com/assets/1902527/21974547/5c91085c-dc02-11e6-82a6-687522e84908.png)

**Comment by fonglh** [comment]
Include #1899.

**Comment by fonglh** [comment]
Might also need instance wide settings.

**Comment by fonglh** [comment]
Include sanity checks such as not sending emails when a course has ended.
