### ISSUE TITLE
Staff should not be able to transfer assessment tab to a category from another course

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1711]
The dropdown is populated incorrectly.

<img width="1004" alt="screen shot 2016-12-12 at 4 28 51 pm" src="https://cloud.githubusercontent.com/assets/6252919/21092932/163b5b98-c08a-11e6-9084-114e11cbf1ea.png">

**Comment by allenwq** [comment]
Fixed in #1744
