### ISSUE TITLE
Modify course settings for open/published/closed to viewable and enrollable

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1713]
Instead of course `status`, to reduce this to 2 booleans:
 - [ ] Viewable: Whether the course is viewable publicly.
 - [ ] Enrollable: Whether non course-staff can enrol into the course. 

This is to support one use case where courses are private but can be enrolled by non course-staff. 

There will be some impact on duplication as well as the migration script.

**Comment by jeremyyap** [comment]
Fixed by #1920
