### ISSUE TITLE
Experience points page does not load if updater is not a course_user in current course

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1717]
For now the experience points record page cannot load unless the updater is a course_user in the current course. To fix this. 

See code here -> https://github.com/Coursemology/coursemology2/blob/master/app/views/course/experience_points_records/_experience_points_record.html.slim#L11-L12

**Comment by allenwq** [comment]
I think this have been fixed in https://github.com/Coursemology/coursemology2/pull/2024
