### ISSUE TITLE
When inviting users, email check should not be case sensitive

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1727]
When inviting users (tested with CSV file), invitation fails if the case of the email address in the CSV file does not match the case of the email stored in the database.

The initial comparison to find the existing user by email is case sensitive, but somewhere downstream is not (probably the validation).

**Comment by weiqingtoh** [comment]
Just check on whether emails are case-sensitive - TLDR, domain isn't, but the local-part might be depending on the implementation of the mail-server.

There is downstream impact: the solution to this is to `downcase` all emails in the CSV file. However, we need to ensure that all emails in the database are also downcased. Looking at the RFC below, it seems like it is not exactly safe to make that assumption.

> ### RFC 5321 2.4. General Syntax Principles and Transaction Model
> SMTP implementations MUST take care to preserve the case of mailbox local-parts. In particular, for some hosts, the user "smith" is different from the user "Smith".
>
> Mailbox domains follow normal DNS rules and are hence not case sensitive

Given this, we can do a solution to downcase only the mailbox domains. What do you think? @fonglh @allenwq 

Sources:
- https://www.lifewire.com/are-email-addresses-case-sensitive-1171111

**Comment by fonglh** [comment]
We just need to implement a case insensitive check for existing user emails when inviting users. Our downstream validation is already case insensitive, and so is the login check.

No need to mess around with the data.

**Comment by allenwq** [comment]
Email stored in our database is already case insensitive, however the validation in the invitation part might have some problems. 

The standard says the local part of the email is case sensitive, but nowadays it's really rare to find a provider that is case sensitive.  And we don't want `name@mail.com` and `nAme@mail.com` to be treat differently and have different accounts in our part, so now our implementation is to `lower` the case before store the email.

So I think we only need to fix the validations.
