### ISSUE TITLE
Provide static URL to attempt assessments

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1737]
There might be a use case to provide a static link for students to attempt a particular assessment - eg. to be posted in announcements. 

The implementation shouldn't be too hard, probably fixes to the controller: add an `attempt` endpoint for each assessment, which does a redirect to submission creation or submission editing page. 

Will have to take note for Surveys and new Video feature as well.

**Comment by allenwq** [comment]
I think `show` page for assessments/survey is a good static link already. we cannot provide a link that actually creates the submissions when the student clicks, as in, we should never use `HTTP GET` to create resources on server.

**Comment by weiqingtoh** [comment]
Is there another way to solve this problem then? 

> There might be a use case to provide a static link for students to attempt a particular assessment - eg. to be posted in announcements.

Could we always do a POST which might not necessarily create resources?

**Comment by fonglh** [comment]
As mentioned previously, the `show` page is sufficient as a static link.
