### ISSUE TITLE
Use user-selected time zone for frontend

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1755]
The frontend currently uses the browser's default time zone, which might not be the same as the user-selected one stored in the backend.

To update after [this PR](https://github.com/yahoo/react-intl/pull/707) has been merged.

**Comment by jeremyyap** [comment]
Note: Firefox does not yet support timezone names, so any client-side solution will not work until Firefox 52 is released (currently scheduled for March 2017)

http://kangax.github.io/compat-table/esintl/#test-DateTimeFormat_accepts_IANA_timezone_names

**Comment by allenwq** [comment]
@jeremyyap we have an `intl` polyfill for unsupported browsers, that should work for these cases.
