### ISSUE TITLE
Allow user to customise lesson plan event types

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#1762]
We currently follow v1 and support "Lecture", "Recitation", "Tutorial" and "Other" only.

- [x] Store event type as string instead of enum
- [x] Change form field to text box instead of drop down
- [ ] ~Allow event types to be pre-populated via settings page.~
    - [ ] ~Write migration to populate initial list from existing event types~
    - [ ] ~Add hooks to add to list when new event type is encountered~
    - [ ] ~Implement settings page view~
- [ ] Change events form to use an auto-complete field for event type
    - [ ] Move forms to React to use MaterialUI Auto-complete component

**Comment by weiqingtoh** [comment]
To support strings that can be input from users. Potentially can mean setting up a new table or involve it in settings.

**Comment by allenwq** [comment]
Actually instead of getting the events from the settings page, how about we populate them using the types from existing events?  

It's easier on the implementation + User won't need to jump the settings page to just add a new type.

**Comment by kxmbrian** [comment]
Yes, I think we should do that. The current plan is for the events form to have a freeform text field instead of a dropdown for event type. The field will have an "auto-complete"-style suggestion but users can type anything (don't need to go to the settings page) and it will be saved as is.

The settings page will allow pre-population of the auto-complete list, but I'm not sure if we have a strong use case for it. Initially thought to use course settings as a cache for the list of event types, but on second thought, it might not be that costly to query for the list each time. Will not implement storage of the list in the course settings for now then.
