### ISSUE TITLE
Preserve material updater and creator when duplicating

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1764]
`creator_id` and `updater_id` are replaced with the id of the user doing the duplicating.

The original `creator_id` and `updater_id` should be preserved instead.

**Comment by weiqingtoh** [comment]
Just a quick consideration - should we have a separate set of ids to track the duplicator instead?

**Comment by fonglh** [comment]
I think it's not necessary to track the duplicator. He's just the guy who invokes the function to copy stuff over. Who last edited/uploaded the stuff is more interesting.

**Comment by fonglh** [comment]
Updater was already fixed in #1723.

**Comment by fonglh** [comment]
`creator_id` also seems to be preserved, but not `created_at`

**Comment by fonglh** [comment]
For the attachment reference, `material.attachment`,  `creator_id` is preserved, but not `updater_id`, `created_at` or `updated_at`.
