### ISSUE TITLE
Allow course_user to change their names

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1766]
Arising from #1761, there is a need to figure out whether: 
 - Students (or `course_users`) can change their names in courses;
 - Course Staff can enable or disable this feature. 

There will be some implications in terms of the registration flow for users, and whether or not they can edit their invitation name at the registration (See PR #1761 for more details).

**Comment by benleong** [comment]
I definitely don't want students to be able to change their names in my
course -- and I might need to be able to change their names within my
course.

**Comment by weiqingtoh** [comment]
Closed. 

Course staff can change course_user names, whilst course_students should not be able to change their own names.
