### ISSUE TITLE
Request to fetch Lesson Plan Items result in inaccurate back button behaviour

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1767]
Steps to reproduce:
1. Go to a course and lesson plan page, wait for it to load
1. Click on any event, eg. assessment
1. Click the back button

A JSON response is seen. Probably something to do with the call to fetch the lesson_plan items adding onto the `history` stack.

**Comment by kxmbrian** [comment]
This is an [issue](http://stackoverflow.com/questions/11966766/hitting-browser-back-button-shows-json-rather-than-html-using-rails-d3-js) for all pages that send a second request to fetch data.
