### ISSUE TITLE
Add help page and content associated with it 

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1784]
To add the following pages: 
 - [x] About Us page
 - [ ] Help page

Issue is who and how to generate content, and how to display it.

**Comment by fonglh** [comment]
`About` page was added in https://github.com/Coursemology/coursemology-theme/pull/13

**Comment by kxmbrian** [comment]
[Help pages](https://github.com/Coursemology/coursemology-help) linked in Coursemology/coursemology-theme#25
