### ISSUE TITLE
Attempting assessments from the todo bypasses assessment description

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1790]
Clicking on the Attempt button on a todo item creates a new submission and brings the student to the submission edit page.

For assessments with additional instructions as attached files, this is confusing for new users as they never see the additional files.

Possible solution:
Go to the assessment description page when there is no existing submission for that student.

**Comment by weiqingtoh** [comment]
I don't think that's a tenable solution, students face the same issue if they try attempting from the `Assessments#index` page. 

If some of the instructions are critical, would it make sense to have that in the assessment description? Then we can show the files together with the assessment description in the `Submission#edit` page (ie. page where student attempts the submission).

**Comment by fonglh** [comment]
So we should show the attached files with the assessment description on the `Submission#edit` page?

**Comment by weiqingtoh** [comment]
There might be other solutions to this too, but I'd prefer not to launch the assessment description page as those result in extra clicks (especially in cases where there are no files).

**Comment by benleong** [comment]
Yes. Pls avoid the extra clicks. Thanks!

**Comment by pottiepie** [comment]
You should just do like v1 and put the assessment description to the top on Submission#edit page and then remove having a separate description page altogether.

**Comment by benleong** [comment]
I am good with that.

You guys frankly suck in your UI/UX decisions. When in doubt, just clone v1.
