### ISSUE TITLE
MCQ/MRQ options orders inconsistent

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1791]
The order of the options are not consistent in question edit page and submission edit page.

Create and question of options in the order of A, B, C. In submission edit page it's C, B, A

- [x] Add weight column
- [x] Drag and drop to re-order
- [ ] Modify the views for question and answer

**Comment by fonglh** [comment]
Used a scope for options instead of modifying the question and answer views to get ordered MCQ options.
