### ISSUE TITLE
Add code view to air mode for code annotations

### ISSUE THREAD

**Issue by Teo-ShaoWei** [Coursemology/coursemology2#1796]

**Comment by jeremyyap** [comment]
Summernote editor does not currently support code view in air mode.
The UI for toggling back to WYSIWYG from code view will be an issue also
Is code view really necessary for code annotations?

**Comment by trangmei** [comment]
> Is code view really necessary for code annotations?

**Comment by trangmei** [comment]
> Is code view really necessary for code annotations?

No
