### ISSUE TITLE
Show Create Course to all Users

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1814]
If user is not able to create course (does not have permissions to do it), to redirect user to page to get them to request to be a lecturer.

**Comment by fonglh** [comment]
This might be very noisy since all students will now end up on the request page and they could just click request for the fun of it.

**Comment by weiqingtoh** [comment]
To implement lecturer request feature first.

**Comment by allenwq** [comment]
@weiqingtoh is this still valid? lecturer request is implemented.
