### ISSUE TITLE
Combine partials for course listing page

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1862]
Specifically `app/views/system/admin/courses/index.html.slim` and `app/views/system/admin/instance/courses/index.html.slim`.

Also, `app/views/system/admin/instance/courses/_course.html.slim` and `app/views/system/admin/courses/_course.html.slim`. 

And also the related translation keys.

Arising from #1860

**Comment by ekowidianto** [comment]
Closed as pages have been moved to react
