### ISSUE TITLE
Split course state into separate options

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1867]
Now there are 3 course states: 
closed ( not published + disallow enrolment )
published (published + disallow enrolment)
opened (published + allow enrolment) 

However, there is a use case for "not published + allow enrolment".  In that case it would be better to use two independent boolean options  ( allow enrolment / publish course )  as what v1 does. And in total there will be 4 possible cases.

**Comment by weiqingtoh** [comment]
Actually is allow/disallow enrolment same/different from registering with code?

**Comment by allenwq** [comment]
You were taking about course code registering or ? 

allow/disallow enrolment is for self enrolment ( i.e send enrolment requests )
