### ISSUE TITLE
Some formatting gets stripped out of comment text

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1868]
If the editor is used to add text effects like background colour, the HTML generated is something like `<p><b>bling full</b> <span style="background-color: rgb(255, 255, 0);">of emails</span></p>`

This is stored in the database but the `span` tags are stripped out when the comment is displayed.

**Comment by weiqingtoh** [comment]
The style attributes are now being stripped from all HTML tags. Was trying to fix this yesterday but I couldn't get to a solution. Will look into this at soon too.

**Comment by jeremyyap** [comment]
I figured out how to whitelist inline css. Which properties to whitelist? Just `background-color` and `color`?
