### ISSUE TITLE
Differentiate between various submission statuses

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1914]
On the assessment's submission list, only "Not Started" is shown in red. Colour coding the other statuses will make it easier to see the outstanding ones.

**Comment by fonglh** [comment]
Now that submission statuses are used as links (#1915), this may no longer be a feasible way to do this.

**Comment by weiqingtoh** [comment]
Still a valid issue, I think the problem is how to differentiate between the different submission statuses.
