### ISSUE TITLE
After "Reset Answer", some answers in tabs disappear until page refresh

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1939]
The code textarea on some of the tabs (looks random) disappears completely. The HTML code is still present in the page source.

Could be related to #1938, which reloads the ACE editor when "Reset Answer" is used.

**Comment by weiqingtoh** [comment]
@fonglh looks fine on my testing on autograded assessments and manually graded assessments (both tabbed and non-tabbed view). 

Can you remember how to reproduce this?
