### ISSUE TITLE
CSV header for upload invitation with CSV

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1943]
CSV might be loaded with or without a header row; to figure out how to prevent the case where the the first row in a CSV file (without headers) is ignored.

**Comment by fonglh** [comment]
The 1st line is currently assumed to be a header.
https://github.com/Coursemology/coursemology2/blob/d118cb7d140cc0902cb1377f2932e0f28445c34e/app/services/concerns/course/user_invitation_service/email_invitation_concern.rb#L75
