### ISSUE TITLE
Implement Lesson plan item settings

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1955]
- [ ] Implement a settings tab
- [ ] In settings tab, allow to permanently hide certain lesson_plan_items (by type - eg. all videos, or a certain assessment tab.
- [ ] In settings tab, allow to hide certain lesson_plan_items by default

**Comment by weiqingtoh** [comment]
For settings, to consider #1964, and merge settings for disabled components. 

 - In settings, implement the display of `lesson_plan_items` and hiding of specific items, eg. 
videos. 
 - Merge this with the course settings when the components are disabled/enabled.

**Comment by kxmbrian** [comment]
Duplicate of #2679
