### ISSUE TITLE
Static attempt link

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1957]
Used for submissions for video and assessments. To also implement for surveys if required.

**Comment by fonglh** [comment]
This means the URL for attempt is always the same, but is redirected to an existing submission/video/survey if it exists, or else it creates a new one and redirects the user there?

**Comment by weiqingtoh** [comment]
Yup - this helps if we need to do some copy pasting!

**Comment by kxmbrian** [comment]
The static link for surveys is `courses/:course_id/surveys/:survey_id`. Users can access the edit page to respond to the survey from there. (#2237)

**Comment by kxmbrian** [comment]
Duplicate of #1737
