### ISSUE TITLE
Disabled components should not show up in lesson_plan page

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1964]
It is possible to create assessments and videos, and disable the component. The assessments and videos will still show up in the Lesson Plan page. The correct behavior is not to show them. 

Currently, the component framework is implemented at the controller level, so perhaps a filter can be added there to filter out disabled components?

**Comment by benleong** [comment]
While you guys are fixing this, add another Lesson Plan tab to the Course Settings to allow instructors to decide what will show. Thanks!
