### ISSUE TITLE
"Graded but not published" submissions in the submissions page should show the grades to teaching staff.

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#1988]
Right now, the grades are also hidden from teaching staff.

**Comment by fonglh** [comment]
They can see them in the submissions page of a particular assessment.

**Comment by luoyanjie** [comment]
> They can see them in the submissions page of a particular assessment
We need to avoid this kind of thinking. The question is not where they can or cannot access something. If something is built but doesn't meet the user needs or is not obvious to the user, then it's as good as wasted. If I were use this logic, by right, we should take out the whole submission page, since everything in there can be accessed elsewhere.

For future clarification, it would be better to question how it matters to the user. The question we should be asking is how it fits into the users' journey.

So Why do users go to submission page? It is a consolidation of what the course has so far. It is a quick way for them to have a sense of the health of the submissions thus far. It is also a quick way for them to decide if they should zoom into  a particular submission or a particular person. 

It is unlike viewing the submissions from a particular assessment as the journey for that is to view the health of the submission of the assessment. But for submissions page? It is from there they see patterns, before they decide if they should zoom into a particular assessment or particular student. 

Hence, it will be important for them to see the grades since it is the information needed to decide if they should zoom into a particular assessment or particular student from the submissions page. ;)

**Comment by weiqingtoh** [comment]
@luoyanjie can you give an example? I tried it and for submissions with `graded but not published` state it seems shows the grade.

**Comment by luoyanjie** [comment]
For reference
![screen shot 2017-02-03 at 12 22 58 am](https://cloud.githubusercontent.com/assets/13025774/22557948/005f7796-e9a7-11e6-88ae-71252fcb66b7.png)
![Uploading Screen Shot 2017-02-03 at 12.23.03 AM.png…]()
