### ISSUE TITLE
Test cases expecting floats may not pass

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1993]
As `assertEquals` is always used, floats may not compare correctly, so student code which is actually correct may be marked wrong.

When the expected answer is a float, use `assertAlmostEqual` instead. Check Python version in which this function is available (should be Python 3.5 and above).

https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual

**Comment by cysjonathan** [comment]
Final decision to not use `assertAlmostEqual`.
From a learning standpoint it will be good for students to learn about floating point errors and how to implement better algorithms to handle floating point errors.
If instructors wish to allow for floating point precision, then they can implement their own rounding check.
