### ISSUE TITLE
Prepend 0 to test case identifiers

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2009]
<img width="306" alt="screen shot 2017-02-08 at 2 19 19 pm" src="https://cloud.githubusercontent.com/assets/1902527/22725669/d25d06ee-ee09-11e6-99a4-e854df2f0905.png">

Test cases are sorted by name when displayed. Python's unittest runner also runs test cases in lexicographical order. As a result, test case 7 comes after test case 10.

Prepend a `0` to single digit test case numbers in the test case creation UI.
Also enforce a hard limit of 99 test cases so a single '0' is enough. Do not allow more test cases because that will increase the chances of hitting the evaluator hard timeout, and would also be very unwieldy.

**Comment by weiqingtoh** [comment]
Fixed by #2061, #2104, #2015
