### ISSUE TITLE
Information leakage when grading assessments

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2015]
- Once submission is `submitted`, student can only see what he/she submitted and comments made up to that point in time. 
 - Tutor's grades, comments and annotation should only be seen by `course_staff` and not the student when the submission state is `submitted` or `graded`.
- For email notifications, no need to email for tutor's comments and annotations, but send a notification when submission state is set to `published`.

To Discuss:
- Should student be able to add comments when submission is in `submitted` or `graded` state? (To clarify with PO before proceeding, need to consider the sudden appearance of posts in the discussion after grades are published)

Tasks:
 - [ ] Prevent leakage through discussion posts (~either disable replying, or hide posts~ by adding additional 'delay comment' feature) once non-autograded submissions are submitted and before being published. (To wait for #1967 to be completed first)
 - [ ] Prevent email notifications for comments and annotations from being sent out unless grades are published.
 - [ ] ~Prevent grades from being seen by students unless published.~ (Grades can only be seen when the submission state is published)

~For assessments with delayed grade publication, students cannot see their grades until the instructor chooses to publish all of them at once.~

~However, email notifications are still sent out for comments and annotations which graders make as they grade the assessment.~

~Also, while the submission stays in a `submitted` state to the students, they are able to see the comments. Graders sometimes place comments indicating where marks are deducted, so this actually bypasses the delayed grade release mechanism.~

**Comment by weiqingtoh** [comment]
Had a discussion with Yanjie - the intended behavior for all submissions for all assessments is:

 - Once submission is submitted, student can only see what he/she submitted and comments made up to that point in time. 
 - Tutor's grades, comments and annotation should only be seen by `course_staff` and not the student.

**Comment by fonglh** [comment]
> Tutor's grades, comments and annotation should only be seen by course_staff and not the student.

How does the tutor give feedback to the student then?

**Comment by weiqingtoh** [comment]
Oops, forgot to state some details - have updated above.

**Comment by fonglh** [comment]
Ok. To add on, email notifications for comments and annotations should also not be sent until the submission state is set to `published`.
