### ISSUE TITLE
[improvement] merge Missions & Trainings sections together

### ISSUE THREAD

**Issue by hongshaoyang** [Coursemology/coursemology2#2021]
as per [this forum post](https://beta.coursemology.org/courses/13/forums/suggestions-on-how-to-improve-coursemology/topics/is-it-possible-to-merge-the-missions-and-trainings-sections-together), a minor suggestion is to merge the Missions and Trainings tabs together as it doesn't make much sense to have different tabs

**Comment by fonglh** [comment]
This is up to the instructor to decide and is not a limitation in coursemology
