### ISSUE TITLE
System announcements feature spec does not handle pagination

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#203]
Leading to spec failure. To reproduce: just run specs locally on your computer a few times, the IDs of the new records would be paginated and not found on the first page.

**Comment by allenwq** [comment]
This is because every time you run the specs on your local, <code>FactoryGirl.lint</code> inserts few records into the database, I still think we need to clear the database after <code>FactoryGirl.lint</code>

**Comment by lowjoel** [comment]
Not really. The tests should actually set the last page, or whichever page that it appears in. Resetting the database is destructive and prevents parallelism.

**Comment by lowjoel** [comment]
This has been masked in recent builds because the announcements are ordered by date descending now. We don't have a solution that properly fixes this, so I'll close this for now.
