### ISSUE TITLE
Duplication of course not working because of duplicated course registration code

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#2042]

**Comment by weiqingtoh** [comment]
This is related to #1799, as duplication for Videos is not done yet. 

@kxmbrian to take note when doing for surveys, you'll need to duplicate the course once surveys is implemented as a component.

**Comment by fonglh** [comment]
I just investigated this one, it's actually because the course in question had set a registration key, which is then duplicated, which the schema does not allow for because the registration key must be unique.
