### ISSUE TITLE
Programming Question UI only works for Python 3

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2055]
Python 2.7 can be selected, but the question generation package hardcodes the `python3` command in the `Makefile`.

https://github.com/Coursemology/coursemology2/blob/master/app/services/course/assessment/question/programming/python/python_makefile#L6

This causes the evaluation to fail as the `python3` binary doesn't exist in the Python 2.7 container.

**Comment by allenwq** [comment]
@justwudi Can you look into this ?
