### ISSUE TITLE
BrainCert API Integration

### ISSUE THREAD

**Issue by xyc0562** [Coursemology/coursemology2#2077]
This feature works like this:

1. The lecturer create a lecture with start_at & end_at
2. Student & lecturer can see the created lecture in the "Lecture" item on the sidebar (much like course announcement)
3. When the lecture starts (that is, when current time is between start_at & end_at of a lecture), both the lecturer and students enrolled in the course can request for a link to access the virtual classroom in the lecture listing page.

I am currently fixing violations identified by Hound and will submit another pull request once done.

@allenwq Let me know if further clarifications are needed.

**Comment by weiqingtoh** [comment]
Fixed by #2081
