### ISSUE TITLE
Wrong phrasing for "Graded but not published" tooltip in "Submissions" page

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#2082]
Tooltip mentioned that user can publish draft grades by clicking on the publish button on top, but there's no publish button on submission page. So remove/edit sentence about publishing.

**Comment by fonglh** [comment]
![screen shot 2017-02-24 at 11 23 26 am 2](https://cloud.githubusercontent.com/assets/1902527/23289326/d7af09f4-fa83-11e6-937b-d7beac41d36c.png)

The tooltip is confusing when on the `Pending Submissions`/`All Submissions` page.

![screen shot 2017-02-24 at 11 25 32 am 2](https://cloud.githubusercontent.com/assets/1902527/23289364/14bf769e-fa84-11e6-8ce2-2b01a70389bd.png)

It is accurate when the tutor is on the submissions page for that particular assessment.

**Comment by weiqingtoh** [comment]
I'll fix this. My fault 😅
