### ISSUE TITLE
Experience Points History shows student name for autograded assessments

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2085]
The `Updater` column for a user's experience points history shows the name of the user who updated the experience points record.

For manually graded assessments, it's the name of the tutor who graded the assessment. However, for autograded assessments, the student's name is displayed. 

Here are 2 possible ways to look at this.

### Show `System` as the updater for autograded assessments

Showing the student's name as the updater is strange as it seems to imply that the student has the power to award himself exp points. Instead, the name shown should be the entity which graded the submission and awarded the points.

Thus for autograded assessments, the updater should be set to the `System` user instead.

### Leave it as it is, showing the student's name as updater for autograded assessments

But it could also be argued that it was the student's action of submitting his submissions that led to the awarding of the exp, so the student's name should be shown.

For manually graded assessments, the grader performed the action of updating the exp and grade, and thus the updater name should be a human.

------------------------------------

@luoyanjie for UX advice please.

**Comment by ekowidianto** [comment]
Wont fix as of now and we will leave it as it is
