### ISSUE TITLE
Destroying instance announcements do not destroy them

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#210]
See `app/controllers/admin/announcements_controller.rb`

**Comment by jsyeo** [comment]
See ![app/controllers/admin/announcements_controller.rb](https://github.com/Coursemology/coursemology2/blob/master/app/controllers/admin/announcements_controller.rb)

**Comment by allenwq** [comment]
How come the tests passed ?

**Comment by lowjoel** [comment]
Reading is failing me.
