### ISSUE TITLE
Investigate the cause of zombie job

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#2103]
The evaluation jobs are supposed to timeout in in 5min if they didn't get picked up by the evaluator. 

Now that some jobs didn't timeout and were in "submitted" state forever.

### Findings & Investigation

Sample zombie job id: `7442b91b-c92d-49e8-9f1a-a73dc6f2472a`
answer_id: `589690`

Another sample zombie job: `2bed93e9-c0f2-440f-bae6-f44441510669`
answer_id: `631003`

**Comment by luoyanjie** [comment]
If zombie job can't be found, implement quick fix to kill job when loading the page.

**Comment by allenwq** [comment]
Did some queries in the database, didn't find any zombie jobs now. will keep monitoring.

**Comment by weiqingtoh** [comment]
Did some investigation - 

### 3 jobs restarted on 23 March Approx 8am
Originating from submissiod_id `47028` - submission has been submitted on 23 Mar at 7.56am, but jobs got stuck, and was restarted when tutor accessed submission at 9.32am. 
Ans_ids: `695307`, `689646` and `689584`.

**Comment by weiqingtoh** [comment]
After #2102, #2167 and #2152, users will not encounter zombie jobs. It will still occur but we have re-try logic to prevent this from happening. We will not look at sidekiq for now, maybe someone when we have spare time.

Will close this for now.
