### ISSUE TITLE
For "Delay grade publication" option, achievements should only be awarded after grade is published.

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#2114]

**Comment by fonglh** [comment]
Related to #2015. I think we should put them under the same issue.

**Comment by weiqingtoh** [comment]
Notes for clarification: 
For an assessment which is a condition, condition is satisfied for a conditional if:
 - Submission is published => for conditions that require a minimum grade.
 - Submission is submitted => for conditions that only require completion of an assessment.

**Comment by weiqingtoh** [comment]
@luoyanjie do you happen to have the details for this incident? The code seems to work correctly, contrary to what was reported.

**Comment by weiqingtoh** [comment]
Investigation: 
Course id: `26`
Assessment id: `1336`
CourseUser id: `1050`
CourseUserAchievement id: `25618` - achivement was created at `2017-03-03 07:35:23`
Achievement id: `596`
Submission id: `41498` - submission was published at: `2017-03-03 07:35:15`

**Comment by weiqingtoh** [comment]
This is a non-issue. Will close.

**Comment by fonglh** [comment]
Thanks for investigating!
