### ISSUE TITLE
Summernote Editor does not have Roboto font in dropdown

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2116]
The default font for the text areas is Roboto, but it does not appear in the dropdown list.

This makes it impossible to switch back after changing the font mid-way.

**Comment by jeremyyap** [comment]
<img width="398" alt="screen shot 2017-03-08 at 2 37 05 pm" src="https://cloud.githubusercontent.com/assets/4056819/23692971/c9357830-040c-11e7-8192-ec8a0359217a.png">
