### ISSUE TITLE
For text response questions, the solutions included the HTML tags from the rich text editor for matching.

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#2130]
- [ ] Allow student answer to have rich-text but strip html tags when comparing
- [ ] Remove rich text editor from solution UI. 
- [ ] Add migration script to strip HTML tags to existing solutions

**Comment by jeremyyap** [comment]
Command to run to migrate existing solutions on production server:

```
Course::Assessment::Question::TextResponseSolution.find_each { |s| s.solution = Sanitize.fragment(s.solution).strip; s.save! }```

**Comment by jeremyyap** [comment]
Most of the formatting options provided by Summernote are purely decorative and can be removed without changing the meaning of the solution, however superscript and subscript may be used for mathematical notation, for example, in questions regarding Big O notation.

If we remove Summernote from the solutions editor, questions requiring superscript/subscript would not be autogradable. Not that they can be reliably autograded currently though.

**Comment by weiqingtoh** [comment]
One of the possible ways to look at this is to extend the math and styled text into other modes of text matching as that is a big can of worms. I understand there is `partial_match` and `exact_match` now - for now, we can move ahead to only support unstyled matching here. 

In the future when there are use cases to match superscript or subscript text, or even math markup, we'll need a different mode to support that (and also have a different set of logic in the autograder).
