### ISSUE TITLE
Order of Courses in Top nav bar Course dropdown is inconsistent

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2166]
The most recent course should be at the top of the list.

**Comment by weiqingtoh** [comment]
@fonglh how do you define the 'most recent course'?

Should we look at the start date of the course, or the end date?

**Comment by fonglh** [comment]
@luoyanjie Can you check with the product owner?

I suspect it might have to be a combination of the 2 dates. For e.g. a short course might be fully "surrounded" by a longer one, but won't be useful for perhaps a couple of weeks after its end date.

I suspect lecturers will want to see their courses from creation until a couple of weeks after end date.

**Comment by ekowidianto** [comment]
my courses are currently sorted by end date.
