### ISSUE TITLE
Fix error - undefined method `zone' for nil:NilClass

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2190]
To reproduce (no need to refresh page anywhere): 

1. Post a comment on a programming file annotation.
2. Post another comment on the same discussion topic. 
3. Click the reply button to bring up summernote text editor. 
4. Delete the post without submitting anything
5. Trigger another reply with the missing post.
6. Type some content, then try to post, error triggered. 

Clicking it again should fix the bug.

**Comment by allenwq** [comment]
Fixed in #2273
