### ISSUE TITLE
Finalize Submission submits the latest answer instead of the latest correct answer

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2300]
For an autograded assessment, it is currently possible for students to 'save (a) draft' of an answer, and then proceed to finalize submission when the student answers the last question correctly. 

What this results in is a [finalization of all latest answers](https://github.com/Coursemology/coursemology2/blob/master/app/models/concerns/course/assessment/submission/workflow_event_concern.rb#L14-L17), which could be wrong, resulting in partial EXP being awarded. This unintended. Rather, the submission should pick out the latest correct answer and award EXP based on that.

To fix this once we figure out the design.

**Comment by fonglh** [comment]
Related to #1959

**Comment by ekowidianto** [comment]
This behaviour is intended and will close this issue now.
