### ISSUE TITLE
Figure out whether to use `yarn build:test` or `yarn build:production`

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2307]
Currently I'm faced with a problem where I `yarn build:test` locally. When testing feature specs locally with javascript, and when there are javascript errors, Poltergeist would catch these and throw a ruby exception, resulting in the feature spec failing. 

However, these errors are not caught in travis because `yarn build:production` is used in the CI server, and for some reason, the feature spec does not fail as long as the capybara assertions are satisfied. 

Hence, to figure out the differences between both `build:test` and `build:production`, and try to resolve this. By right, the CI and local environment should have a reasonable amount of parity to avoid any friction.

**Comment by allenwq** [comment]
`yarn build:production` is used for CI mainly for:
1. Ensure that the test suite uses the same assets file as production, so we will know if the assets have any problems in production.
2. Faster to run the entire test suite when using production assets, the assets are optimized in both size and performance.

The alternative is to rename `yarn build:test`,  or stick with `yarn build:production` in local.

**Comment by ekowidianto** [comment]
Non-issue now
