### ISSUE TITLE
Make saving of sidebar ordering settings more robust.

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2350]
As of commit a1287079ddf7bf3868ba57ff2ed262635ecdd65e, with virtual classrooms enabled but no sidebar order settings in the `settings` column of the `courses` table,  the following JavaScript error occurs.

`An invalid form control with name='settings_sidebar[sidebar_items_attributes][1][weight]' is not focusable.`.

With virtual classrooms disabled, sidebar ordering works and the settings are populated, but stops working again when virtual classrooms are enabled.

At commit 688004c14620965adba6dedbb11ffb01cfe3e7b2, when virtual classrooms are disabled and then re-enabled, sidebar ordering works again and the settings are populated.

This problem is different from #2321.

### Hypothesis

Missing sidebar ordering settings and maybe the renaming of virtual classrooms causes incorrect HTML/JS to be generated, causing the JS error. Disabling then re-enabling virtual classrooms causes the settings to be correctly populated.

However, it is unclear exactly which difference in the 2 commits solves the problem.

#2119 could be a contributor.

**Comment by allenwq** [comment]
Fixed in #2547.
