### ISSUE TITLE
Inviting a user already in the course fails with unhelpful error

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2358]
![image](https://user-images.githubusercontent.com/1902527/28235861-f79d77de-6949-11e7-8b3a-41704e6185b5.png)

If the user is already in the course and the same email is used to add him/her individually, the unhelpful error shown in the screenshot above is displayed.

In this test, the user was present as a phantom teaching assistant. Try scenarios where the user has a different role and is not a phantom.

## Solution

Detect duplicates when inviting and tell the user what happened.

**Comment by weiqingtoh** [comment]
Solved by #2434
