### ISSUE TITLE
Upgrade to material-ui v5

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#2438]
1.0 uses a very different way to do styling, thus need to change quite some of our existing code (especially the styling part). Better upgrade to that earlier before more and more React code are added in.

We will get better performance and the DOM nodes are cleaner since the styles are not mixed.

However, from my test there are still some issues. we at least need to wait for the following two to be closed:
~~https://github.com/callemall/material-ui/issues/5524~~
~~https://github.com/callemall/material-ui/issues/5716~~

**Comment by jeremyyap** [comment]
There are some components Material UI has decided **not** to implement in V1 and we have to look for third-party implementations or build our own components if we want to upgrade.

https://material-ui-next.com/demos/autocomplete/
https://material-ui-next.com/demos/pickers/
