### ISSUE TITLE
Forum poster's name overlapping with content when too long

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#2473]
When a word in the name is too long, it will spill into the forum post. Suggest to implement `word-break` and `ellipsis` properties for the relevant CSS class.

**Comment by luoyanjie** [comment]
[Uploading Screen Shot 2017-08-28 at 10.27.34 AM.png...]

**Comment by jeremyyap** [comment]
@luoyanjie is the styling in #2047 okay? Can we use that instead?

**Comment by luoyanjie** [comment]
@jeremyyap sorry didn't notice this. It is fine but the profile picture should be inside the post header next to the name. In that way, the indentation would be clearer to the user visually.
