### ISSUE TITLE
Handle case where programming question output is too long

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2484]
There are instances where the STDOUT can be too long, to figure out how to implement a size limit.

**Comment by fonglh** [comment]
What happens when `stdout` is too long? Is it just a display problem or does something break?

**Comment by allenwq** [comment]
Evaluator will die, too long means can be few GB of data. This could happen when the student has print statements in an infinite loop.

**Comment by weiqingtoh** [comment]
@fonglh this is solved by #2557? Anything else we should/need to do?

**Comment by fonglh** [comment]
No I think that's it.

Fixed by #2557.
