### ISSUE TITLE
Create user clickable links for all existing parts

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#249]
We have implemented a few parts, but there is no links be shown on UI, we need:

Dropdown to admin panel, current path is: <code>/admin</code>
Link to system announcement, current path is: <code>admin/system_announcements</code>
Link to instance management, current path is: <code>admin/instances</code>
Link to create course, current path is: <code>courses/new</code>
Link to course settings, current path is: <code>courses/:id/settings</code>

**Comment by lowjoel** [comment]
#295 implements courses, #284 implements admin.

Course settings already fixed in #268.
