### ISSUE TITLE
Separate global and instance admin panel

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#250]
We want to make global announcements on global admin panel and do instance specific settings on instance admin panel

**Comment by lowjoel** [comment]
What are the things you can do in the global admin panel? Apart from adding and removing instances, and adding announcements, what else can you do?

**Comment by lowjoel** [comment]
> We should also have a view of all the courses and users across the whole system. Simple statistics for the system. 
Potentially, we will eventually have reporting tools on each of the instances as well.

**Comment by lowjoel** [comment]
As agreed yesterday, we will have one global admin panel, also handles the case that there are multiple instance admins.
