### ISSUE TITLE
Need to check answer is not empty, before submission.

### ISSUE THREAD

**Issue by huangjosh** [Coursemology/coursemology2#2507]
Right now, even if the learner does not input anything, he can still submit the answer.
It would be better to ensure learner does not submit empty answers.

**Comment by benleong** [comment]
Given that the required validation will depend on the question type, I'm not sure why can cannot go ahead to fix each type independently. The problem for voice inputs is that it's v v easy to screw up. The other types not so easy to screw up.

**Comment by huangjosh** [comment]
@benleong Just confirmed with the team. The team actually want to put the validation for audio question into a separate pull request instead of putting validation for all the question types into a separate pull request. I think I will submit a pull request again to add validation for audio question.

**Comment by huangjosh** [comment]
Validation for audio question is merged in https://github.com/Coursemology/coursemology2/pull/2564
