### ISSUE TITLE
Autograding for text answer (exact match)

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#251]
### Summary

Allow the lecturer to specify correct and wrong answers. Use the answer key to automatically grade short answer questions.
### Background

Coursemology v1's general mission questions allow for open ended text answers. Shuqun Secondary would like an auto grading feature for this type of questions. This is useful for short answer questions where very specific keywords are expected.
### Implementation Notes
1. Like a coding question, the lecturer specifies answers for each question. The auto grader checks for an exact match with the answers.
2. While the coding auto grader gives a grade depending on how many test cases are correct, this text auto grader should probably give full credit as long as there is an exact match with any answer. This will allow lecturers to specify a few of the most likely acceptable variants.
3. The lecturer can also specify wrong answers. For each answer, he can write a comment with a more detailed explanation of why the answer is correct or wrong.
4. Just like for coding questions, the automatically assigned grades are meant as guidelines for the tutor to check before finalising the grade.

**Comment by kxmbrian** [comment]
Implemented in #641
