### ISSUE TITLE
Result based dependencies

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#253]
### Summary ###
1. Must score at least x % to unlock the next task. This implies that repeated submissions are possible.
1. Ensure that students attain a minimum level of competency in one topic before moving on to the next one.

### Background ###
Mission dependencies are currently binary. When you're done, you can move on. This feature ensures that you also have to meet a minimum competency before you can move on.

### Implementation Notes ###
1. The lecturer can specify a minimum grade, or percentage of the maximum grade, that must be met before the student can move on to the next mission.
1. This feature implies that repeated submissions are possible. The existing scheme requires the tutor to unsubmit the mission before the student can try again. In allowing multiple submissions, missions will become more like trainings.

**Comment by weiqingtoh** [comment]
This has been implemented already. To close. 

Lecturer can specify a minimum grade percentage for any assessment conditions.
