### ISSUE TITLE
Keyword based marking

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#254]
### Summary

Assisted grading of essay questions based on keywords.
### Background

Marks per keyword to be entered into an answer scheme. Default marks based on keywords. Graders can modify.

This has some similarities to auto grading for text answers. However, keyword based marking is more suitable for longer answers in the form of paragraphs.
### Implementation Notes
1. The lecturer specifies keywords which are expected to show up in the answer and assigns marks for each one. Multiple keywords can be added for each question. The grading assistant helps by highlighting the keywords and automatically assigning a grade.
2. The tutor can then edit the assigned grade depending on whether the keyword was used correctly.

**Comment by lowjoel** [comment]
@fonglh I think currently we now support this, can this be closed? See the implementation we have.

**Comment by kxmbrian** [comment]
Implemented in #641
