### ISSUE TITLE
cherry-picking dup does not migrate category/tab if not selected

### ISSUE THREAD

**Issue by Teo-ShaoWei** [Coursemology/coursemology2#2601]
For the cherry-picking dup, if we just check the box for individual assessments without checking the category/tab up the ancestor tree, the assessments seem to not be migrated, or they are migrated but orphaned.

So if say I am duping `Mission 10`, I will need to check `Mission` and `default` which are it's ancestors category and tab respectively, else the dup will fail.

Might it be better if we always migrate the ancestor category/tab for selected assessments, regardless of whether they are ticked or not? Then we reserve the tick beside them for mass select/de-select of the whole category or tab... what do you think?

**Comment by kxmbrian** [comment]
The item should have been copied to the destination course's default folder. Can you find it? The 'checkout dialog' was supposed to inform the user of this behavior.

The current implementation aims to give the user the most control/flexibility, but if majority of the instructors prefer this behavior, we can implement it. We don't have `draft` categories or tabs yet, so one minor side effect are students seeing cats and tabs dis/appearing as the instructor edits.

One possibility is to allow the user to select the destination in the same interface. A small trade-off for that is a more cluttered and complicated UI.

**Comment by Teo-ShaoWei** [comment]
Ah I see I see, yes it is found inside:- https://nanyangjc.coursemology.org/courses/1193/assessments?category=1307&tab=1864
I will go ahead and delete them as I have re-duplicated so you might not see it when you visit the page anymore soon.

So what I understood is that for this case, the default course assessment is Lecture Trainings, if nothing is selected it will appear there.

Actually there is a similar issue if we check the category/tab box too, a new tab will be created that house these migrated assessments.

Either way require much follow-up action of moving assessments one-by-one to the right location, which might be error-prone.

Since the use-case is for cherry-picking instead of bulk transfer, this is the time when we want finer control in what gets moved to where. So in this case, my opinion is that the selection of destination in the UI, as you suggested, is a worthwhile trade-off.

Anyway, now that I know how it works, it's a small issue. I think you are in a better position to decide on how to best optimise this.

**Comment by Teo-ShaoWei** [comment]
![screen shot 2017-10-23 at 11 08 56 am](https://user-images.githubusercontent.com/6925907/31870859-b6374ec2-b7e2-11e7-9e1c-f8cfd1a3e75d.png)
Here is the screenshot, with the migrated missions. They could be accidentally hidden amongst valid assessments, but as long as the default after-migration status is unpublished, then it isn't a game-breaker, just inconvenience.

**Comment by weiqingtoh** [comment]
Closing since no action required.
