### ISSUE TITLE
Migrate to Rails 5 new framework defaults

### ISSUE THREAD

**Issue by jeremyyap** [Coursemology/coursemology2#2617]
Split out from #2271 

See `config/initializers/new_framework_defaults.rb` for details

- [ ] `Rails.application.config.action_controller.raise_on_unfiltered_parameters = true`
- [ ] `Rails.application.config.action_controller.per_form_csrf_tokens = false`
- [ ] `Rails.application.config.action_controller.forgery_protection_origin_check = false`
- [ ] `ActiveSupport.to_time_preserves_timezone = false`
- [ ] `Rails.application.config.active_record.belongs_to_required_by_default = false`
- [ ] `ActiveSupport.halt_callback_chains_on_return_false = true`

**Comment by vietlami** [comment]
but it not work
