### ISSUE TITLE
Object Duplication target course dropdown is empty if user is not an instructor in other courses

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2648]
Instead of showing an empty dropdown, show an explanatory message instead.

Perhaps something like:

`You are not an instructor in any other courses.`

**Comment by kxmbrian** [comment]
This is permissions issue that only affects super-users.

Normal users should never see a blank dropdown since if the can see the interface, they should be able to duplicate back to the same course. So, the dropdown should contain the name of the course they are currently in.

**Comment by fonglh** [comment]
#2653 was the proposed implementation, but after discussion with @luoyanjie, it was decided to show the sidebar item and display an error page instead.

```
Sorry, this feature is only for course managers and owners. 

Please ask the course owner for the necessary rights to duplicate data from his/her course.
```

**Comment by kxmbrian** [comment]
The empty dropdown does not occur anymore after #2921.
