### ISSUE TITLE
Duplication time shift uses the start of day as the default

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2649]
With the switch to React for the duplication frontend, the datepicker library has changed.

When selecting a target course start date, the library now defaults the time to the start of the day. It's more sensible to use the same start time of day as the original course.

Possible solutions:

1. Set the time with JS after the user has selected the target course's start date.
2. See if the library has options or parameters that can be passed in to aid with correct time selection.
3. Have the backend read the date from the frontend, but ignore the time component passed from the JS and use the original course's start time of day instead.

**Comment by kxmbrian** [comment]
This was a choice on my part, not the fault of the library. Agree that it makes sense to use same start time as original course.
