### ISSUE TITLE
Configurable lesson plan

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2679]
Allow instructors to select which items are shown on the lesson plan.

**Comment by fonglh** [comment]
Fix #1964 first.

**Comment by kxmbrian** [comment]
Duplicate of #1955. Key points:
- Staff can choose which types are shown/hidden by default. Students can unhide showable items that are hidden by default.
- Staff can choose which types are showable from the list of components that are enabled. Disabled components cannot be made showable and should be excluded form the settings list.
- When displaying the list of showable items, ensure items are set as showable by staff AND items belong to components that are enabled.

**Comment by kxmbrian** [comment]
Implemented for Assessments in #2742
Implemented for Surveys and Videos in #2750
