### ISSUE TITLE
Figure out how to include C code in comments

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2691]
C code is sometimes removed when included in comments. To investigate and fix, eg.

```c
#include <stdio.h>
```

**Comment by jeremyyap** [comment]
Not straightforward to escape disallowed/invalid HTML tags: rgrove/sanitize#139

The other way to solve this would be to reimplement the rich text editor for comments.

**Comment by jeremyyap** [comment]
Resolved in #2857
