### ISSUE TITLE
Create abstract Settings class for pan-component settings

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2731]
Component settings which inherit from `Course::Settings::Component` automatically get settings confined to their component.

However, there are some settings which span across components (pan-component settings). Examples include email notifications and lesson plan item display. These involve settings from different components (e.g. assessments, videos, surveys).

As a result, `Course::Settings::Notifications` and `Course::Settings::LessonPlanItems` both need to query all the other components to get the relevant settings.

Some of the common code regarding the querying across various components could be abstracted out into a base `Course::Settings::PanComponents` class, similar to what `Course::Settings::Component` does for individual components.

See https://github.com/Coursemology/coursemology2/pull/2722#discussion_r159827640 for background.

**Comment by weiqingtoh** [comment]
This is fixed already
