### ISSUE TITLE
Toolbar covering first row and some buttons not working

### ISSUE THREAD

**Issue by Agentzhao** [Coursemology/coursemology2#2823]
When making a new question in an assignment. 
1. Toolbar is covering the first row
2. Highlighted buttons on the toolbar are not working
![coursemology](https://user-images.githubusercontent.com/20024592/35846452-b09c3bea-0b51-11e8-86d5-cee7b2f7dac8.PNG)

**Comment by fonglh** [comment]
We just deployed https://github.com/Coursemology/coursemology2/pull/2811, which downgrades the Summernote editor.

Is this still a problem for you?

**Comment by Agentzhao** [comment]
It's fixed now, thank you!
