### ISSUE TITLE
Show all posts when replying to a forum post

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2859]
Currently when replying for a forum post, clicking on the reply brings up a separate window. This window now only shows the main post being replied to. 

To modify page to show all the posts of the entire chain associated with the replying of that post.

**Comment by jdg006** [comment]
I'd like to take a crack at this issue. Is there anything else about this issue I should know before getting started?

**Comment by weiqingtoh** [comment]
@jdg006 not really - perhaps on top of trying to set up coursemology in your local machine, you might want to familiarise yourself with the structure of the posts, before getting started on the feature itself. 

What I can suggest is that if you have questions, please do join the Coursemology slack group and reach out to us 😃
