### ISSUE TITLE
Summernote inline code button tooltip displays [object Object]

### ISSUE THREAD

**Issue by taneliang** [Coursemology/coursemology2#2870]
To reproduce:

1. Go to a comment box which renders a `ReactSummernote` component in air mode (e.g. in a submitted submission).
2. Type something into the comment box.
3. Double click the text.
4. In the resulting popover, mouseover the inline code button. The tooltip will say "[object Object]" instead of "Inline Code".

![screenshot_20180314_205644](https://user-images.githubusercontent.com/12784593/37403576-365688fa-27ca-11e8-8c8a-3bc1ccccd79b.png)

This cannot be reproduced when `ReactSummernote` is not in air mode (e.g. in the forums). I've also only tried this on Chrome 64.0.3282.140 on Linux.

This bug is likely to be caused by [this line](https://github.com/Coursemology/coursemology2/blob/49a6d7fc906377b8d7a73c1186e7515a7876c79c/client/app/lib/components/MaterialSummernote.jsx#L108), which passes in a React element as the tooltip instead of a string as specified in the [Summernote docs](https://summernote.org/deep-dive/#custom-button).

**Comment by hongshaoyang** [comment]
on a side note, does anyone know the keyboard shortcut for changing text to inline code?

**Comment by jeremyyap** [comment]
Inline code is a custom button and no keyboard shortcut for it has been implemented yet.

This might be useful for implementing a custom keyboard shortcut https://github.com/summernote/summernote/issues/104#issuecomment-60993410
