### ISSUE TITLE
Resizing window closes annotation comment box, causing comment to be discarded 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Coursemology/coursemology2#2871]
To reproduce: 

1. Open any coding assignment submission and open an annotation box 
2. Type something into it 
3. Resize the browser window until the layout changes 
4. Notice the previously opened annotation box is now gone, along with the written content 

Expected behaviour: 

The annotation box should remain open, or at least the contents should be preserved when the box is reopened.

**Comment by hongshaoyang** [comment]
+1

**Comment by trangmei** [comment]
Annotation comment box no longer responds to window resizing event, but is manually toggled, after https://github.com/Coursemology/coursemology2/pull/3479

**Comment by ekowidianto** [comment]
Fixed in #3479
