### ISSUE TITLE
Insert link dialog appears below overlay when opened from annotation box

### ISSUE THREAD

**Issue by ZhangYiJiang** [Coursemology/coursemology2#2878]
To reproduce: 

1. Open any coding assignment 
2. Open an annotation box on the code 
3. Enter some text, select it and try to add a link either via Ctrl + K or clicking the toolbar UI button 
4. The opened dialog has the overlay appears _on top of_ the dialog rather than the other way round 
5. The dialog now cannot be closed unless you hit ESC on the keyboard 

![screenshot from 2018-03-19 16-27-15](https://user-images.githubusercontent.com/445650/37585141-0909e55a-2b93-11e8-83ce-88617d48a6ce.png)

This does not happen if the dialog is opened from the comment box below each answer.

**Comment by jeremyyap** [comment]
summernote/summernote#978
