### ISSUE TITLE
React screens do not load on production

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2898]
Currently an infrequent bug that is self healing; the basic symptom is that react does not load on some assessment pages. Not much real actions to reproduce yet, but opening an issue to track the information gathered so far: 
 - Bug occured once when user tried to attempt assessment. Once that happens, it fails to load after that.

**Comment by cysjonathan** [comment]
Closed due to inactivity and issue no longer seems to be observed/reported.
