### ISSUE TITLE
User Terminology

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#290]
- Course Owner
- Course Instructor
- Course TA
- Course Student

?

**Comment by kxmbrian** [comment]
Some school teachers have assistants that handle admin, but not necessarily teaching. Perhaps "Course Assistant"?

**Comment by lowjoel** [comment]
Would we be duplicating roles?

**Comment by allenwq** [comment]
We have a manager role now, which is kind of assistant ?

**Comment by kxmbrian** [comment]
This seems to have been resolved. Okay to close it?

**Comment by allenwq** [comment]
Think so
