### ISSUE TITLE
Keyboard Shortcut (Alt-enter) to Run Programming Code

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2935]
UI Suggestion: In each assessment submission view, it would be good to have a keyboard shortcut for programming questions (when the programming text-editor is rendered) to automatically run programming code. This is similar to other platforms (eg. repl.it) which uses the same shortcut for code execution.

**Comment by cysjonathan** [comment]
Closed by #4028 
Use Ctrl + enter / Cmd + enter (for mac)
