### ISSUE TITLE
Cache yarn/webpack output for travis

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2942]
Currently each container builds this separately, plus it takes quite a long time (~90s). To figure out how to cache this if there are no javascript changes.

**Comment by fonglh** [comment]
https://docs.travis-ci.com/user/caching/

**Comment by fonglh** [comment]
Unlike bundler, `yarn build:production` doesn't check if the output files with the same hash already exist before generating the output.

It might be necessary to figure out how to store the hash in the cache as well then add a check to decide if the yarn command should be run.
