### ISSUE TITLE
Support summative assessments without human intervention

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#2990]
The current assessments in Coursemology are either `AutoGraded` (AG) or `Non-AutoGraded` (NAG). Currently all NAG assessments require `course_staff` to go in to award points and EXP for the submission. 

There is a use case to allow for summative assessments without human intervention, where points and EXP are awarded automatically based on some auto-graded rubric (programming qn: number of test cases passed, text response qn: number of text matches etc.)

This is partly to support summative assessments (assessments which do not allow retries) for Programming and GP Comprehension Question.

No clear idea of how to implement this yet, but it could be a new mode, or an enhancement on AG assessments (disable retries).

**Comment by cysjonathan** [comment]
Closed by #3023, through the use of "allow submission with incorrect answers" toggle.
This allows students to submit and be awarded grade and EXP based on the number of test cases passed.
