### ISSUE TITLE
Update codeclimate-test-reporter

### ISSUE THREAD

**Issue by jeremyyap** [Coursemology/coursemology2#3001]
[codeclimate-test-reporter](https://github.com/codeclimate/ruby-test-reporter) has been deprecated. We should switch to the new codeclimate test reporter, which is no longer a gem but a downloadable executable file instead.

[Sample CI configuration](https://docs.codeclimate.com/v1.0/docs/travis-ci-test-coverage) for the new test reporter

>PARALLEL AND MULTIPLE TEST SUITES
>The Code Climate test reporter can join multiple test reports together from separate test suite processes. Uploading partial test coverage data after a batch of tests and fetching all partial test coverage data after all batches complete is a DIY process. We recommend syncing and fetching files from S3 as one approach.

**Comment by ekowidianto** [comment]
Closed as codeclimate-test-reporter gem has been removed
