### ISSUE TITLE
Autograded programming assessments

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#3023]
When "Autograded" is enabled, allow assessment owner to:

1.  choose which type of test cases are used for grade/exp calculation:
- [x] Add to assessment edit form: one switch for each type of test cases
- [x] Migration to add corresponding boolean fields with default values to course_assessments table
- [x] Modify autograding service to calculate grade accordingly

2. indicates whether students are allowed to submit answers without passing all public+private test cases:
- [x] Add to assessment edit form: one switch to allow submission of partially correct answer, default to false
- [x] Migration to add corresponding boolean field with default values to course_assessments table
- [x] Change renderFinaliseButton()

**Comment by trangmei** [comment]
Always allow students to submit without having all correct? Or only when "Use evaluation tests for grade/EXP" is enabled?

**Comment by trangmei** [comment]
Future work:
https://github.com/Coursemology/coursemology2/issues/2561
