### ISSUE TITLE
Allow forums to be re-ordered

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#3048]
Forums are currently ordered by creation time.

Add an order column and allow instructors to change the order of the forums in the course.

**Comment by trangmei** [comment]
hey @wn96 do you want to try this?

**Comment by wn96** [comment]
sgtm

**Comment by knmnyn** [comment]
Bump.  This would be a very useful feature that I would use right away.  Currently I have to retitle my existing forums to get them to be reordered -- lucky my course hasn't started yet.

**Comment by trangmei** [comment]
Similar existing feature: course settings > sidebar ordering
