### ISSUE TITLE
SummerNote toolbar cuts off first line of response editor for free-response questions

### ISSUE THREAD

**Issue by takuyakanbr** [Coursemology/coursemology2#3063]
![abc](https://user-images.githubusercontent.com/875036/44399221-4dd17a80-a579-11e8-8ad4-db66e2afd527.png)

As shown in the image above, the first line of the response is hidden behind the toolbar. This seems to occur only after scrolling the page, on both Google Chrome 68 and Firefox 61.

**Comment by fonglh** [comment]
This is caused by the addition of `style="height: 45px;"` to the `<div class="note-toolbar-wrapper panel-default">` when scrolling up.

**Comment by benleong** [comment]
@fonglh @trangmei  Can we fix this soon? This is v irritating.
