### ISSUE TITLE
Keyboard shortcut to Submit New Comment

### ISSUE THREAD

**Issue by hongshaoyang** [Coursemology/coursemology2#3064]
Similar to issue #2935 (Keyboard Shortcut (Alt-enter) to Run Programming Code), it would be good to have a keyboard shortcut (eg Ctrl-Enter) for marking coding questions (where the programming text editor is rendered) to submit a new comment so that we don't have to click the "Comment" button

![image](https://user-images.githubusercontent.com/19281800/44452952-782f4080-a62a-11e8-807f-650af696cd10.png)

**Comment by dexterleng** [comment]
```
export default class CommentField extends Component {
  componentDidMount() {
    document.addEventListener('keydown', this.onKeyDown);
  }

  componentWillUnmount() {
    document.removeEventListener('keydown', this.onKeyDown);
  }

  onKeyDown = (e) => {
    const { createComment, value, isSubmitting } = this.props;
    if (e.altKey && e.key === 'Enter' && !isSubmitting) {
      e.preventDefault();
      createComment(value);
    }
  }

  render() {
    ...
  }
}
```

I've "done" it, problem is that when Ctrl-Enter is pressed a newline (<br>) is created before submission. Any ideas how to do it without modifying MaterialSummernote?
