### ISSUE TITLE
Two hamburger buttons

### ISSUE THREAD

**Issue by trangmei** [Coursemology/coursemology2#3065]
![image](https://user-images.githubusercontent.com/35135264/44459721-3a87e300-a63d-11e8-9057-9d38b24ccbef.png)

**Comment by benleong** [comment]
@trangmei Sounds like a bug?

**Comment by trangmei** [comment]
each of them expands to a different set of menus. i think there meant to be 2 buttons.
Maybe i'll change the icon for one of them and align how they expand.

**Comment by benleong** [comment]
@trangmei Can we merge into one hamburger?

**Comment by benleong** [comment]
@trangmei I know the problem -- one hamburger is for the top navbar. One is for the left navbar. Maybe we just put the left navbar one on the left instead of putting them side by side?

**Comment by cysjonathan** [comment]
Technically, the left hamburger is a dropdown for the sidebar
(Announcements, Assignments, ..) and
does not overlay over the screen like the right hamburger (Courses, Help,
..) does.

A mobile user who scrolled far down the page, and taps on the left
hamburger will see any visible change.
A non-experienced user may think the left hamburger is spoilt.

Perhaps either position the left hamburger dropdown as absolutely overlayed
over the screen (like the right hamburger dropdown does)
or reposition the hamburger together with the profile picture and
user-sidebar elements, so the user will definitely see the sidebar slide
out on tap?

**Comment by nicholasluimy** [comment]
![picsart_09-04-12 52 52](https://user-images.githubusercontent.com/8996422/45010750-99882780-b041-11e8-8137-e74ddc6e496f.png)
Something like this?

**Comment by fonglh** [comment]
For coursemology.org, this has to be fixed in the [theme repo](https://github.com/coursemology/coursemology-theme)

**Comment by trangmei** [comment]
Hi @fonglh I don't have access to push my branch
