### ISSUE TITLE
Cannot create inline comment after assigning grade to any question

### ISSUE THREAD

**Issue by zxjtan** [Coursemology/coursemology2#3089]
After assigning a grade to any question in an assignment, clicking the + sign to add an inline code comment crashes the page and shows:

Something went wrong.

Error: Permission denied to access property "nodeName"

in n in div in div in t in InjectIntl(t) in t in div in t in div in div in t in t in t in Connect(t) in t in withRouter(Connect(t)) in div in div in t in td in tr in tbody in table in t in t in t in Connect(t) in t in t in withRouter(t) in value in i in Connect(i) in n in div in t in t in InjectIntl(t) in div in t in n in form in div in div in t in t in t in InjectIntl(t) in Form(InjectIntl(t)) in Connect(Form(InjectIntl(t))) in t in t in Connect(t) in t in t in t in t in t in IntlProvider in i in t in g

**Comment by fonglh** [comment]
Just tried and it works for me.

Try force refreshing the page with Ctrl + F5 as your browser might be using a cached version of the JavaScript files.

If that still doesn't work, send an email to the address on the contact page with the URL of the assignment you're having a problem with.

**Comment by zxjtan** [comment]
It breaks on all assessments, but turns out it's because I was using Firefox. Is it one of the supported browsers?

**Comment by fonglh** [comment]
I just tried it on Firefox and it's still working. Maybe try clearing your cache?

**Comment by zxjtan** [comment]
Nope, still broken. I figured out that it only breaks when full marks is given for any one question in any assessment.

**Comment by fonglh** [comment]
Closing as there's no further feedback.
