### ISSUE TITLE
Filepicker for upload does not validate that a file is selected

### ISSUE THREAD

**Issue by nicholasluimy** [Coursemology/coursemology2#3172]
<img width="315" alt="screen shot 2018-10-29 at 11 12 10 pm" src="https://user-images.githubusercontent.com/8996422/47659538-22e65100-dbd0-11e8-987f-f49ad0448826.png">
If the upload button is clicked with no file selected, a blank 400 error page is thrown

**Comment by jeremyyap** [comment]
Issue occurs on the material folders material upload page.
