### ISSUE TITLE
Make dropdown menu on duplication page more obvious

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#3195]
The small downward-pointing grey arrow is insufficient to indicate to user presence of a drop-down menu. Could make more obvious by putting a grey outline or shadow around the menu.

![image](https://user-images.githubusercontent.com/1902527/48194461-0b555800-e388-11e8-9389-492779d68d2e.png)

**Comment by gkpacker** [comment]
Hey @fonglh! I'd like to work on this!

**Comment by fonglh** [comment]
Yes do go ahead.

**Comment by gkpacker** [comment]
Done! Can you take a look, @fonglh? Thanks in advance!
