### ISSUE TITLE
No error messages  for manual course invitation.

### ISSUE THREAD

**Issue by dexterleng** [Coursemology/coursemology2#3258]
Mentioned by @trangmei  in #3151:
> error handling can be improved maybe in a separate PR, because it is currently the same buggy behavior as course invitation.

Right now it just redirects to `/courses/1/users/invite` when there is a rollback.

Maybe the success message can be similar to that of invites from CSV:
![screen shot 2018-12-19 at 5 06 14 pm](https://user-images.githubusercontent.com/34204380/50211455-a55ee600-03b3-11e9-8ce2-7c901980fb46.png)

**Comment by trangmei** [comment]
Yeah this alert message looks good

**Comment by fonglh** [comment]
Is it possible to show 2 flash messages? A green one that indicates success, and a blue info one if there are any duplicates.
