### ISSUE TITLE
Practical Exams for Coursemology

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#326]
Figure a way to allow Coursemology to be used with practical exams.

Potential problems:
- [x]  How to prevent students from accessing a PE before/after the start/end time
- [ ]  How to prevent communication between students during a PE
- [ ]  How to prevent students from using other courses as a communication channel
- [x]  How to ensure that only students within the exam venue can attempt the PE (password protect?)
- [x]  Code evaluator needs to have independent test cases

**Comment by fonglh** [comment]
Use an assessment-wide password which will only be issued to students in the room.

Grades must be released to students at the same time.

**Comment by allenwq** [comment]
> How to prevent communication between students during a PE
> How to prevent students from using other courses as a communication channel
Students can always register a new account, and they could use different accounts to communicate. I think there's no way to only rely on Coursemology to prevent all these. 

I am going to close this as password protected assessment is implemented and used in PE. we can open new issues to discuss PE related problems.
