### ISSUE TITLE
Update submissions index page to show assigned total grade

### ISSUE THREAD

**Issue by louietyj** [Coursemology/coursemology2#3389]
References #3388

Need to find a way to efficiently retrieve all total grades at one go and pass down to React.

**Comment by louietyj** [comment]
Same thing for download submission statistics

**Comment by ekowidianto** [comment]
Solved by #4206 - https://github.com/Coursemology/coursemology2/commit/8e14565971a9e1cf14382f274cfeda1a72aae28e
