### ISSUE TITLE
Nag users into verifying email accounts instead of blocking them

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#346]
Email verification is necessary because we need to send notifications to users. However there will be students who forget their email account passwords and Facebook passwords. In other cases, the verification email sent by Coursemology might be delayed.

In these circumstances, it can be frustrating for teachers who need to resolve these administrative issues.

Allow Coursemology to let users to sign in even if they have not verified their accounts, but display a nag screen for users to verify their emails.

**Comment by cysjonathan** [comment]
Closing this as we will continue to enforce email verification.
Final decision was to not allow users to use the platform without email verification.
