### ISSUE TITLE
simple_form cannot deduce column types of inheritied attributes

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#349]
Course::Event acts_as Course::LessonPlanItem
![screen shot 2015-06-18 at 5 06 06 pm](https://cloud.githubusercontent.com/assets/6252919/8227770/5d230736-15dc-11e5-9196-e6d91fcce666.png)

Failed detection of attribute types:
![screen shot 2015-06-18 at 5 06 58 pm](https://cloud.githubusercontent.com/assets/6252919/8227791/870ec184-15dc-11e5-9ea0-659dd9818bff.png)

**Comment by allenwq** [comment]
The acts-as gem probably did not delegate `column_for_attribute` to parent model.

@kxmbrian You can also manually specify the column type by using `as:` option,  e.g. `f.input :title, as: :string`

**Comment by lowjoel** [comment]
Probably need to PR.
