### ISSUE TITLE
Improve warning text for deleting tab

### ISSUE THREAD

**Issue by aaronhojw** [Coursemology/coursemology2#3504]
After clicking on the delete tab icon, the modal that pops up should not only say "Are you sure" but also notify the teacher that the assessments contained in the tab will also be deleted if teacher clicks "yes".

**Comment by AndreiUngur** [comment]
Hi ! :wave:
I've tackled this for `categories` as well, with the message
```
This action will delete all assessments associated with this <tab | category>. Are you sure?
```
Please let me know if this message is what you had in mind!

**Comment by trangmei** [comment]
@AndreiUngur thank you very much for the PR.

Should the message be changed to:
`Deleting this <tab | category> will delete all associated assessments. Are you sure?`

to avoid using `This`

**Comment by AndreiUngur** [comment]
@trangmei Thanks for the feedback. I agree with that formulation being a little better so I've updated my PR accordingly! :smile:
