### ISSUE TITLE
Course teaching staff do not see tab management buttons in course video settings

### ISSUE THREAD

**Issue by knmnyn** [Coursemology/coursemology2#3525]
I believe that the video settings is supposed to allow instructors to configure additional tabs for organizing videos within types (CS1010X seems to have this capability:
![image](https://user-images.githubusercontent.com/217067/58494659-324e6c80-81a8-11e9-8151-d89270a8b8bf.png)
where "Lecture", "Tutorial" and "Recitation" are tabbed views to filter the videos.  But in the video settings page I can't seem to add an addition tab:
![image](https://user-images.githubusercontent.com/217067/58494718-53af5880-81a8-11e9-81a3-648a7ba3d148.png)

Reporting from Chrome / MacOS.

**Comment by benleong** [comment]
That's correct.

**Comment by fonglh** [comment]
Course teaching staff do not seem to see these buttons.

**Comment by knmnyn** [comment]
Yes, that's right.  I cannot see the button. 
![image](https://user-images.githubusercontent.com/217067/58497551-c4597380-81ae-11e9-9be0-1c98c65ea81e.png)

**Comment by trangmei** [comment]
Do you want to add this ability for teach staff? That means TAs also can create new videos tab.

**Comment by trangmei** [comment]
Oh I see what you mean, i'll take a look
