### ISSUE TITLE
Compiler error when evaluating C++ code for programming questions

### ISSUE THREAD

**Issue by nianfei97** [Coursemology/coursemology2#3552]
When trying to evaluate the answers for a programming question in C++, the following error messages appear, causing all tests to fail:

stdout:
`cat tests/prepend.cc submission/template.c tests/append.cc tests/autograde.cc > answer.cc`
`g++ -isystem /home/coursemology/googletest/googletest/include -g -w -Wall -Wextra -pthread -std=c++11 answer.cc /home/coursemology/googletest/googletest/libgtest.a -o answer.bin`
`Makefile:21: recipe for target 'answer.bin' failed`

stderr:
`g++: internal compiler error: Killed (program cc1plus)`
`Please submit a full bug report,`
`with preprocessed source if appropriate.`
`See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.`
`make: *** [answer.bin] Error 4`

Occasionally, re-evaluating the answers resolves the problem, but this has failed more and more frequently and with an increasing number of submissions.

**Comment by fonglh** [comment]
Have you tried increasing the memory and time limits for the question?

**Comment by nianfei97** [comment]
This appeared to have resolved the problem for the few submissions that were previously problematic. I will close this issue after we have run through all submissions and confirm that this has resolved the problem.

For reference, could I know what the default memory limit is? We did not set any memory limit on the assignment previously and left the "Memory limit" field blank.

**Comment by fonglh** [comment]
https://github.com/Coursemology/coursemology2/blob/000aa8ec2721e2d7956f11307accb37d1d19e0a8/lib/autoload/coursemology_docker_container.rb#L26

There is also a maximum time limit of 30 seconds.
https://github.com/Coursemology/coursemology2/blob/master/app/models/course/assessment/question/programming.rb#L9
