### ISSUE TITLE
Allow Survey description / titles / surveys to be editable / delete

### ISSUE THREAD

**Issue by knmnyn** [Coursemology/coursemology2#3568]
Right now, surveys sections can be added/deleted but not surveys themselves.
It would be helpful to have this functionality.

**Comment by benleong** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/1297525/59749278-5127b680-92af-11e9-88fc-85c62000f91b.png)

**Comment by fonglh** [comment]
You cannot edit/delete surveys in courses where you are an observer.

**Comment by knmnyn** [comment]
Oh crap, thanks.  I didn't get the vertical ... UI hints to find the corresponding actions.  My bad.
