### ISSUE TITLE
Logging in forces me to download galaxy-note8_design_planet_start.jpg

### ISSUE THREAD

**Issue by knmnyn** [Coursemology/coursemology2#3593]
Not sure why, but when I login to Coursemology from a new browser, submitting the login form causes my browser to download galaxy-note8_design_planet_start.jpg from Coursemology.

**Comment by knmnyn** [comment]
I can't replicate this under private browsing though.

**Comment by benleong** [comment]
We're looking into this problem.

I just complained yesterday. >_<
