### ISSUE TITLE
Inline Code button doesn't work

### ISSUE THREAD

**Issue by zxjtan** [Coursemology/coursemology2#3621]
Tried in Attempt page comment boxes, both inline and question comments, both with and without Show Comments Panel toggled. Clickable and the button toggles but the text does not change.
Firefox 68.0 Linux

**Comment by trangmei** [comment]
Context is undefined here https://github.com/Coursemology/coursemology2/blob/master/app/assets/javascripts/layout.js

due to deprecation of context:
https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed
