### ISSUE TITLE
Support manual reordering of Materials and Videos

### ISSUE THREAD

**Issue by knmnyn** [Coursemology/coursemology2#3646]
As above.  It would be good to add this, via a DB column for viewing order, that when specified, could be reflected in the student view.

**Comment by fonglh** [comment]
Videos are ordered by start time, which is consistent with assessments. Materials are ordered by name.

This is sufficient to achieve a custom order without a separate DB column.

**Comment by knmnyn** [comment]
So the name needs to be in alpha order to get it sorted then, correct @fonglh ?
