### ISSUE TITLE
Reusing docker containers

### ISSUE THREAD

**Issue by dexterleng** [Coursemology/coursemology2#3744]
Is this something I could potentially explore for improving evaluation performance?

I noticed jsreport is reusing containers and thought it would be an interesting problem to work on:

https://jsreport.net/learn/docker-workers

**Comment by cysjonathan** [comment]
Can we first profile what the evaluation performance is currently, to see if it is worth optimizing on this?
Currently the bottleneck for docker (failing) seems to occur during periods of high-loads, which can be solved using a queue system.

jsreport looks like a commercial licensed project though, which makes it incompatible with Coursemology's open-source nature.

Happy to make Coursemology code evaluation more efficient, but let's see close first and re-open this issue once we get some statistics of the time-benefits of recycling containers.
