### ISSUE TITLE
Past answers file viewer vulnerable to XSS

### ISSUE THREAD

**Issue by takuyakanbr** [Coursemology/coursemology2#3760]
When viewing past answers for an assessment that is not submitted, the code viewer for file-submission programming questions appear to render arbitrary HTML elements.

This issue does not seem to occur after the assessment is submitted.

Example: [[coursemology.org]](https://coursemology.org/courses/1824/assessments/33917/submissions/917524/edit) (select "View Past Answers" on Q1)

This also affects the correct rendering of code:
![coursemology](https://user-images.githubusercontent.com/875036/76622066-b7561700-656b-11ea-9837-2eb5219956db.png)

**Comment by cryptoAlgorithm** [comment]
This is interesting, I wonder if this vulnerability still exists on the latest version? I might try to test it out (on a self hosted instance of course 😀)
