### ISSUE TITLE
Fix Email Service

### ISSUE THREAD

**Issue by zhengwei143** [Coursemology/coursemology2#3826]
Currently using SendGrid as the email service to send out our emails, however we are currently using a shared IP plan which cause certain email domains to be blocked (yahoo, hotmail) due to the poor reputation of the shared IP address.

Previously used Amazon SES but Coursemology was banned due to many emails being flagged as spam by users. Amazon SES requires a system implementation that allows users to unsubscribe to the emails (currently unavailable - only allows users to unsubscribe from forum threads) before they will lift the ban.

Possible fixes:
- Upgrade SendGrid to a dedicated IP (downsides - expensive, upsides - easy/quick to implement)
- Change to another email service (likely to have similar issues to SendGrid and also similar pricing)
- Add implementation to allow users to unsubscribe to emails and change back to Amazon SES

**Comment by raymondtangsc** [comment]
@benleong cheapest dedicated IP plan for SendGrid costs $89.95/month. Let's upgrade to that for now, but figure out a path forward for Amazon SES in medium term ? (3-6 months)

**Comment by ekowidianto** [comment]
@zhuhanming @cysjonathan would like to seek input on the UI/UX below

**Admin email setting page**
![image](https://user-images.githubusercontent.com/42570513/136143758-b1a8cfec-203f-45a5-8c2c-cd545b6b7635.png)

**Staff email subscription page**
![image](https://user-images.githubusercontent.com/42570513/136143798-fc4e8db3-4647-4be1-b572-17775f86aff9.png)

**Student email subscription page**
![image](https://user-images.githubusercontent.com/42570513/136143816-c83c53a7-fe1d-4bed-b718-cdc8787fa0df.png)
