### ISSUE TITLE
Updating Survey submissions

### ISSUE THREAD

**Issue by ShreyasKp** [Coursemology/coursemology2#3879]
While using Coursemology, the teaching staff of CS3244 has encountered some issues regarding updated submissions of Coursemology surveys-

1. Coursemology surveys do not update the submission time for the latest submission. When a current submission gets edited, the submission time reflects the time of submission of the first attempt.
2. Currently, submitted surveys can be updated even after the survey expiry time as well.

**Comment by benleong** [comment]
The former could be a bug. We can check.

For the latter, there are settings:
![image](https://user-images.githubusercontent.com/1297525/97255419-88b35500-184b-11eb-84e3-e0a866006aba.png)

Anonymity might be a bit broken also.

**Comment by ShreyasKp** [comment]
Hi Prof Ben, 

Thanks for replying. 

To clarify the issue on survey updates, we created the survey with only the option 'Allow Submitted Responses to be Modified' selected while **not selecting** 'Allow Responses after Survey expires'. We haven't tried out the Anonymity feature yet but noted on that!
