### ISSUE TITLE
Should we allow students to unsubmit their own missions if it is a contest?

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#4]
This is open for discussion, and would affect the architecture of the new Assessments module.

**Comment by benleong** [comment]
I guess it's possible to have an optional setting in a mission (defaulting
to False) to allow a student to self-unsubmit before an assignment is
graded. This might generate race conditions, but I guess those who want
this have to take the risk. We can issue a warning when the option is
checked.
