### ISSUE TITLE
Feature for students to download all uploaded files

### ISSUE THREAD

**Issue by SuibianP** [Coursemology/coursemology2#4033]
The current feature seems to only allow copy-paste but not downloading (single or batch). It is frequently useful for students to be able to download all files in a question together (for example, in order to debug locally).

**Comment by RussellDash332** [comment]
I'm not sure if every course has the Workbin section where there is actually an option to download all the files in a specific directory altogether.
![image](https://user-images.githubusercontent.com/63991775/132138942-6a10481c-156d-4c15-992e-7a91da51f2e7.png)
