### ISSUE TITLE
Need more informative text on Achievement delete button

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4155]
![image](https://user-images.githubusercontent.com/10083037/139944638-32c43444-dcd5-4472-98dc-0eb90e7167a2.png)
Tutor blur, delete badge instead of unchecking box for a single student.
Confirmation should state:
```
Are you sure you wish to delete the Achievement: <achievement name>?
This will cause <num_students> user(s) who have already attained this achievement to lose it.
```

**Comment by cysjonathan** [comment]
At the same time, to do a search through entire application for any other dialogs that uses "Are you sure?" without further elaboration.

**Comment by ekowidianto** [comment]
Part of react migration
