### ISSUE TITLE
Image duplication fails during course duplication

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4167]
### Description of issue
Course 2147 has some images uploaded, on course duplication, the images are broken.
Currently the duplication will still go through even though images do not duplicate #4162 

### Demonstration
https://coursemology.org/courses/2147/ has an image uploaded
https://coursemology.org/courses/2149/ image has broken

https://coursemology.org/courses/2147/achievements/ has an image uploaded
https://coursemology.org/courses/2149/achievements/ image has broken

During duplication, logs show Carrierwave::DownloadError (could not download file: 400 "Bad Request"

### Timeline of events

1. 9 Sep 2019 Upgrade to Carrierwave 2.0 #3641 
2. 13 Sep 2019 Fix double encoding of URI in Carrierwave 2.0 #3652
3. 10 Oct 2019 Failed duplication during course duplication discovered #3677 
4. 14 Oct 2019 Downgrade of Carrierwave and removal of double encoding fix #3680 
5. 30 Sep 2021 Upgrade of Carrierwave to 2.1.1 #4083

Since URI encoding not yet fixed in 2.1.1, we are likely encountering the same error, conversations in Carrierwave's repository about the error here:
[upgrade from 1.3.1 to 2.0.0 breaks remote_x_url when coming from s3](https://github.com/carrierwaveuploader/carrierwave/issues/2415)
[Encoding strategy change causes sadness with previously uploaded files?](https://github.com/carrierwaveuploader/carrierwave/issues/2428)

### Possible resolutions
- Downgrade Carrierwave back to 1.3.1
- Upgrade to >=2.2.0 Fix for this issue comes in [Carrierwave >=2.2.0](https://github.com/carrierwaveuploader/carrierwave/commit/3faf7491e33bd10ae8b3e0010501fc96a76c21c3) 17 Jan 2021, will have to test as there _may_ be [other issues](https://github.com/carrierwaveuploader/carrierwave/issues/2482)

**Comment by ekowidianto** [comment]
carrierwave upgrade to 2.2.0 fixes duplication for achievement badge but not course logo. Unduplicated logo error is fixed in #4179
