### ISSUE TITLE
Track duplication of course material

### ISSUE THREAD

**Issue by zhuhanming** [Coursemology/coursemology2#4224]
We may want to keep track of how course content has been duplicated across courses, so as to be able to "trace" these duplications and potentially allow for some comparisons, e.g. are students now performing better with the same course content? etc. There may be other potential gains from tracking these duplications as well. Eventually, we would aim to have a DAG of course content.

However, the challenge lies in determining when a duplicated course content, which can be subsequently modified, is no longer the same as the original. It's somewhat like the Ship of Theseus problem.

Open to discussion. We brought this up in one of the earlier meetings but didn't have anything too conclusive.

Another idea along the same vein is the generation of FAQ based on forum posts from previous course iterations.

**Comment by cysjonathan** [comment]
Eventual discussion led to the conclusion that a single question can belong to multiple assessments.
Related to the schema change involved here: #2246 #2629

We should then implement a "copy-on-write".
Unless there is only a single reference to the original question, then an update is fine.

This will allow multiple references to the same question (e.g. submissions across multiple instances/courses and batches of students reference the same question).
For access control, access should stem from course level. (e.g. If question exists in courses A, B, C, D, and I am instructor for only courses C and D, then I am only able to see "history" for submissions in C and D.)

At a higher level, we can look at implementing the same feature for videos, achievements, surveys, etc.
