### ISSUE TITLE
Move views for creating and updating conditions from RoR to React

### ISSUE THREAD

**Issue by lyskevin** [Coursemology/coursemology2#4242]
<img width="1398" alt="Screenshot 2021-12-27 at 12 56 55 PM" src="https://user-images.githubusercontent.com/37838247/147435971-a0dc1652-8f83-4a6f-b1bd-a2d4314f494b.png">

Currently, when editing a conditional, the conditions list appears as a React component.

<img width="1427" alt="Screenshot 2021-12-27 at 12 59 56 PM" src="https://user-images.githubusercontent.com/37838247/147436121-0be63e5b-8328-4d81-9414-100f5cd2a8bb.png">

However, when performing actions on conditions themselves (e.g. creating or updating a condition), the app navigates to a separate page where an RoR view for the relevant action is rendered.

We want to move the RoR views into React so that they can be reused (currently, each condition type has its own set of RoR views) and also remove page navigation (i.e. creating and editing conditions will take place on the conditional editing page).

**Comment by ekowidianto** [comment]
Closed in #5154
