### ISSUE TITLE
Submissions filter query should be optimized

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4276]
Wai Kay has reported that this page takes long to load.
![image](https://user-images.githubusercontent.com/10083037/147778232-27e98ffb-a3d5-4a45-a70c-cc65a5d3a41b.png)

Current investigation shows that this is partially due to cancancan behaviour #2599.

When checking for the role in the course user table, cancancan takes the long route as the specific ability is not specified here. 

https://github.com/Coursemology/coursemology2/blob/5456decc087249ba939ad46219fe92c63e2ab3e4/app/controllers/course/assessment/submissions_controller.rb#L50

Since there are multiple abilities for assessment submission (see below), some long table joins are then included which is actually not necessary.

https://github.com/Coursemology/coursemology2/blob/5456decc087249ba939ad46219fe92c63e2ab3e4/app/models/course/assessment/assessment_ability.rb#L86-L90

Do we need to consider the case where instructors only have access to a subset of submissions?
e.g. in a polytechnic, instructor of class Monday may not want instructor of class Tuesday to view their students submissions.

In that case, should we handle access by group level?

**Comment by ekowidianto** [comment]
Updated the description above for root cause of the performance degradation.

```
Do we need to consider the case where instructors only have access to a subset of submissions?
e.g. in a polytechnic, instructor of class Monday may not want instructor of class Tuesday to view their students submissions.

In that case, should we handle access by group level?
```
- possible to do and we can just add it in the future when needed

**Comment by ekowidianto** [comment]
comparison of the table query for the following line between normal user vs coursemology admin user

https://github.com/Coursemology/coursemology2/blob/5456decc087249ba939ad46219fe92c63e2ab3e4/app/controllers/course/assessment/submissions_controller.rb#L50

## *normal user*
![8780B6C8-35F9-4F7F-845C-CB2FABC9216C](https://user-images.githubusercontent.com/42570513/147881961-39797743-939d-4ae2-b528-99fdbb29750b.jpeg)

## *Admin user*
![62C02F92-C064-4409-9D3B-B82725EC533E](https://user-images.githubusercontent.com/42570513/147881966-fac19863-4b98-43c1-bbc4-dcc4817016fc.jpeg)
