### ISSUE TITLE
Submission can enter an invalid state when instructor updates maximum grade of question

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4287]
![image](https://user-images.githubusercontent.com/10083037/148699431-d0d59c9e-02ec-454a-a5d5-b4f23dd20fa3.png)
To replicate issue:
1. Set a question for maximum grade of 10
2. Create a submission and submit a correct answer to be awarded grade value 10
3. Now update question Question is updated to have a maximum grade of <10 (e.g. 1).
4. Submission is now in an invalid state since current grade > maximum grade
5. Unsubmission or deletion of submission fails

Excerpt of logs:
```
F, [2022-01-09T20:15:56.726878 #16] FATAL -- : [x]
[x] ActiveRecord::RecordInvalid (Validation failed: Grade must be less than question maximum grade):
[x]
[x] app/models/concerns/course/assessment/submission/workflow_event_concern.rb:157:in `block in recreate_current_answers'
```

Expected behaviour, to discuss:
When maximum grade of question is updated, do we:
1. Do nothing (current behaviour)
2. Scale the grades of marked submissions accordingly e.g. 10/10 becomes 1/1, 5/10 becomes 0.5/1
3. Cap the grades of the marked submissions to the new maximum. e.g. 7/10 becomes 7/8 if max is reduced to 8. But if max is reduced to 5, then new grade is 5/5.

During unsubmission or deletion, there should not need to validate submission grades since all grades will be voided/nulled.

**Comment by benleong** [comment]
I think do nothing. 

The current problem is that when we try to unsubmit/delete a submission, we are doing redundant validations.
