### ISSUE TITLE
Backfill duplication implementation

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#431]
Depends on #427.

**Comment by fonglh** [comment]
This is being worked on in https://github.com/coursemology-collab/coursemology2/tree/fonglh/duplication-controller

Starting with the 'Whole course duplication' section. The code will be refactored and could be modified significantly later on to support the other 2 requirements.

## Whole course duplication
- [ ] Duplicate a course (title, description, shift start/end times)
- [ ] Duplicate the rest of the course information

## Selective duplication
- [ ] Display items which can be duplicated
- [ ] Capture user selection
- [ ] Duplicate selected items to a new course

## Cherry picking
- [ ] Show target courses
- [ ] Duplicate selected items to an existing course
