### ISSUE TITLE
Trim empty lines from summernote input

### ISSUE THREAD

**Issue by zhuhanming** [Coursemology/coursemology2#4337]
Currently, MCQ / MRQ can look weirdly spaced if there are trailing lines from summernote:

### Settings

<img width="1193" alt="Screenshot 2022-01-26 at 7 32 21 PM" src="https://user-images.githubusercontent.com/45617494/151155971-cb13a897-38ee-4215-985f-b4526276da5a.png">

### Question

<img width="1193" alt="Screenshot 2022-01-26 at 7 32 51 PM" src="https://user-images.githubusercontent.com/45617494/151156036-fc106fea-fc23-4872-a639-9c9f06712280.png">

After looking more into this, it seems like all summernote inputs are currently not being trimmed across the application, which gives us text with training `<br>`, `<p></p>`, etc. that has no content.

It would be good to perform some trimming on such inputs. Potentially, it can be a function tied in to the summernote component itself, since this seems like view-level logic to me.

**Comment by cysjonathan** [comment]
No longer using summernote. Using CKeditor that does not have this issue.
