### ISSUE TITLE
Email spam when assessments are graded

### ISSUE THREAD

**Issue by zhuhanming** [Coursemology/coursemology2#4340]
One feedback from students is that the number of emails sent when the grading is happening, e.g. when tutors leave comments, can be quite significant.

I think this may become even more of an issue now due to the delayed comments, which can potentially blast off comments written over a long period of time all in one shot.

Perhaps we can look into the batching of emails or the summarising of multiple (related) emails into a single digest. Might be harder to implement for non-delayed comments, since it's not clear-cut how long we should "debounce" for the individual emails.

**Comment by ekowidianto** [comment]
There is no email sent for delayed comments after a submission has been graded. Students only get 1 email which is the graded submission notification.
