### ISSUE TITLE
autograder failing for unknown reason

### ISSUE THREAD

**Issue by dezhanglee** [Coursemology/coursemology2#4344]
For example, this student (Question 1):: https://coursemology.org/courses/2167/assessments/48432/submissions/1416105/edit
The test case function is also not working for other students

The same question and setting has been used many times in previous iterations of the course with no issue. This question was copied over from previous iterations. 

Increasing the time limit and switching between the different versions of Python 3 does not help. 

Can you please advise on what we can do about this? Thank you.

**Comment by cysjonathan** [comment]
Hi dezhanglee, closing this issue as the autograders seem to be running fine at this point.
