### ISSUE TITLE
forum: Text in angle brackets disappears on post edit

### ISSUE THREAD

**Issue by kokrui** [Coursemology/coursemology2#4347]
1010X student here who noticed this while using the forums - when creating a forum post/reply with angle bracket characters, in the Code View it looks like Summernote successfully encodes them into their respective HTML entity chars (`&lt;` or `&gt;`). 

(I realise this first gif might be a bit misleading - the angle bracket chars **are** shown correctly in the forum once the post here is created)

![angle-newpost](https://user-images.githubusercontent.com/29654756/152077461-67a2be7e-6c64-4f30-96e2-18f88eb229e9.gif)

However, when a user goes to **edit** the post, the text within the angle brackets is now interpreted as an HTML element. 

(the angle brackets and the text within them will no longer show in the forum once the post is updated)

![angle-edit](https://user-images.githubusercontent.com/29654756/152077771-418132a9-b6da-40e9-90f8-032f4803308e.gif)

**Comment by kokrui** [comment]
btw, noticed that as of #4151 the `react-summernote` package is now on a private repo - would it make sense to have it as a git submodule somewhere on this repo instead? so that there won't have to be parallel PRs and parallel forked repos for any coursemology changes involving summernote behaviour

**Comment by kokrui** [comment]
this occurs as long as there's a `&lt'` (`<`) character immediately followed by any letter or exclamation mark (with no spaces in between). a "closing" `&gt;` (`>`) char isn't necessary, and if omitted the rest of the text will be included into the html element and not shown on screen

it doesn't seem to be anything in `posts_controller.rb` or the `application_html_formatters_helper.rb` - with the `@post.text` being `abc abc abc &lt;lol abc abc <br>`, both `helpers.sanitize` and `helpers.format_html` return the text unchanged. 

but the Summernote component on the Edit Post screen shows:
```html
abc abc abc <lol abc="" abc<br="">
</lol>
```

**Comment by ekowidianto** [comment]
Wont be fixed as we are moving to full react page
