### ISSUE TITLE
Submitted autograded assessment has wrong answers when "Allow submission with incorrect answers" setting is disabled

### ISSUE THREAD

**Issue by ekowidianto** [Coursemology/coursemology2#4446]
This happens when a student does not submit a changed answer (either only save draft or answer is changed and finalize submission is clicked).

To check if the submission form is dirty or there's any answers that are not submitted before allowing submission finalisation.

**Comment by cysjonathan** [comment]
When not allowed submission with incorrect answers, finalize submission button is greyed out (cannot click)

Student submit correct codes (all correct)
Finalize submission (can click)
Student edit their answer without pressing submit
Finalize submission (can click)
Click finalize submission

Track frontend changes to prevent submission.
"Please submit again, or revert to previous answer"
