### ISSUE TITLE
Invalid SSL Certificate

### ISSUE THREAD

**Issue by wxxedu** [Coursemology/coursemology2#4491]
My browser refuses to load Coursemology because the SSL certificate for Coursemology seems to have expired.

<img width="1439" alt="CleanShot 2022-04-03 at 08 04 32" src="https://user-images.githubusercontent.com/36021591/161406889-78e92fa0-3597-4afb-9d72-04f6cc4b9262.png">

**Comment by cysjonathan** [comment]
Thanks for raising this. Cert has been renewed, so will be closing this issue.
Will have to revisit this sometime next year April before the next stated expiry on Friday, 5 May 2023
