### ISSUE TITLE
When on mobile or devices with small screens, some elements are reachable in current display

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4529]
https://coursemology.org/courses/2183/assessments/51320/submissions/1491127/edit

![image](https://user-images.githubusercontent.com/10083037/163730395-864dfaa0-34db-457f-aafa-6d5279a94520.png)

When there are too many questions/content to fit in the current container width, the parent will overflow, but there is no horizontal scrolling available, so some elements become unreachable for visual observation.

Known affected elements (overflow-x, unable to scroll horizontally):
1. Question "nav" tabs
2. Autograder test cases

**Comment by Madiena** [comment]
Hello (: I'd like to contribute to this project by solving this issue. I'd also appreciate a short reply before I start. Thank you.

**Comment by cysjonathan** [comment]
Hi Madiena, have you used Coursemology before?
You will have to create your own branch using this convention `<nickname>/<description-of-feature>`, then submit a Pull Request once tested and ready to be merged. (e.g. `madiena/fix-submission-ui-overflow`)

**Comment by ekowidianto** [comment]
Note that this only happens in mobile view

**Comment by Madiena** [comment]
> Hi Madiena, have you used Coursemology before? You will have to create your own branch using this convention `<nickname>/<description-of-feature>`, then submit a Pull Request once tested and ready to be merged. (e.g. `madiena/fix-submission-ui-overflow`)

I personally haven't used Coursemology before. Do you have any further information about contributing for me?

**Comment by Madiena** [comment]
Nevermind. I've found the contribution guide (:
