### ISSUE TITLE
System jobs to remind users to submit survey should update Last Reminder Sent At

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4581]
# What is the issue

The system generated reminder to students to complete their survey is sent 24 hrs before the closing of the survey
![image](https://user-images.githubusercontent.com/10083037/167541969-4a43b124-a83c-4da5-9ae1-c9380a447b40.png)
However, the Last Reminder Sent At field does not reflect that the last sent was 9 May 2022 12pm
![image](https://user-images.githubusercontent.com/10083037/167541948-9a210880-ed6d-47cb-aaf3-997b782b90bd.png)

# Expected behaviour

Scheduled reminders triggered within the system should also update the Last Reminder Sent At.

**Comment by syoopie** [comment]
Error cannot be reproduced
