### ISSUE TITLE
Improve Groups management interface

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4591]
Desired behaviour:
- [x] Display number of people in each group
- [x] Clicking on row entire should support selection of user instead of the checkbox
- [x] Staff should be set as Manager by default
- [x] Select All/Unselect all
- [ ] ~~Support transfer between groups~~ TBD

Also linked to #4401

**Comment by purfectliterature** [comment]
Seems like the groups already show total number of people.

![image](https://user-images.githubusercontent.com/51525686/183345418-d6acbc9d-594c-42b7-8039-d867290bd176.png)
