### ISSUE TITLE
Course Surveys warning instead of disabling the submit button

### ISSUE THREAD

**Issue by RussellDash332** [Coursemology/coursemology2#4634]
When student fails to answer all survey questions, give an explicit warning that they didn't answer all the questions instead of just making the submit button not work.

**Comment by ekowidianto** [comment]
@leeroy999 Can add a tooltip to inform the user

**Comment by cysjonathan** [comment]
I actually think we should follow other forms behaviour
button not disabled, but when clicked, it will scroll to the first unanswered question, and highlight (usually in red) the questions that are not yet responded.

**Comment by RussellDash332** [comment]
I believe this is resolved via either #4599 or #4606?
![image](https://user-images.githubusercontent.com/63991775/182455280-00eafd6b-3230-4965-8121-6d7ae63e58ff.png)

The problem now is that the Save button works exactly the same as the Submit button. So if I want to save, I still have to fill in all the fields first, which should not be the case

**Comment by ekowidianto** [comment]
Fixed in #4940
