### ISSUE TITLE
Confusing icon in new 'Add announcements' UI

### ISSUE THREAD

**Issue by chrisgzf** [Coursemology/coursemology2#4829]
![image](https://user-images.githubusercontent.com/4933577/178277482-7247a14d-1735-467d-b1f4-621b3e579b1c.png)

I was a little confused when I was trying to add an announcement. IMO Icon buttons should indicate intent, which means that I would have preferred it if the icon button to add an announcement was a '+' instead of a paper symbol.

**Comment by syoopie** [comment]
Solved with #4862
