### ISSUE TITLE
'Invite users' form state resets after submission

### ISSUE THREAD

**Issue by chrisgzf** [Coursemology/coursemology2#4879]
# Repro steps

In the "Invite Users - Users" page

1. Type a new student's name, email, set role in dropdown as "Student", set Phantom switch to true.
![image](https://user-images.githubusercontent.com/4933577/180638525-a6a36595-416f-47ea-84c1-343712382c16.png)

2. Click "Invite all users"
3. New dialog pops up that says "No new users were invited"
![image](https://user-images.githubusercontent.com/4933577/180638564-d913a75a-2b13-402e-8009-75f7f0fb2be9.png)
4. Somehow form state resets and my new user is shown as not being a phantom student.
![image](https://user-images.githubusercontent.com/4933577/180638676-d0053e3c-65c7-4e35-863e-ef0418cad5c4.png)

I was very confused because I was like huh... did I not set the new student's phantom status correctly?

# Expected Behaviour

Either you clear the entire form on success (my student is already added successfully, why do I still need his entry there?) or make the form reflect accurately what the user has put in previously, which is that I added a Phantom student. Former is better.

# Side note about point 3

![image](https://user-images.githubusercontent.com/4933577/180638564-d913a75a-2b13-402e-8009-75f7f0fb2be9.png)

This feels a bit misleading and confusing btw. I know what is trying to be conveyed here, which is that no new user is added to Coursemology because they already have an account, but this is vague phrasing. I was confused because as a user I was like, "huh, didn't I just add a new user to the course? Why does it say no new users were invited?"

As a user, I'm more concerned about whether my add action was successful or not, which is not super clear right now in this screenshot. There is also no intent styling (green boxes or something) to indicate that it is okay. True that I might be curious how many were added but don't have Coursemology accounts, and if so, it should be phrased that way. As an example,
```
numWithoutAccounts > 0 && `${numWithoutAccounts} user${numWithoutAccounts > 1 ? "s" : ""} without Coursemology accounts have been added to the course. Email invitations have been sent to them.`
```

**Comment by qreoct** [comment]
Thank you @chrisgzf for the detailed notes and feedback!
