### ISSUE TITLE
N+1 queries when running specs

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#489]
After #469 there are failing specs when Bullet.raise_error is set to true and running the specs. Apparently when moving the initializer I didn't specify to raise in specs.

**Comment by lowjoel** [comment]
@allenwq has Bullet been enabled in tests?

**Comment by allenwq** [comment]
I think I misunderstood this issue, I thought all tests passed already. But we probably won't enable bullet anymore in test, I remember it's false positive ?

**Comment by lowjoel** [comment]
Yes, the idea is to solve the false positives in Bullet itself, so that the tool is sensitive to mistakes.
