### ISSUE TITLE
Further Improvements

### ISSUE THREAD

**Issue by syoopie** [Coursemology/coursemology2#4910]
These are are the collated improvements that have not been implemented across all of my PRs.

**All courses page (/courses):**
- [x] ~~Use pluck for backend SQL~~ (Page query is not expensive and loading speed is quite fast now).
- [x] ~~Implement backend pagination~~ (Page query is not expensive and loading speed is quite fast now).
- [x] ~~Sort by~~ (Dont think there is a need for now since we have search feature).
- [x] ~~Sign out -> Go to all courses page -> Request to be instructor -> Sign in as administrator -> Brings to role request page (An admin is the highest and should not need to file a role request)~~ (Keep for now as the endpoint is not visible to end user)
- [x]  ~~Users can manually type in /courses/role_request/new and submit multiple role requests, when they should only be allowed to edit the existing role request. They can only access these "extra" role requests by manually typing in /courses/role_request/:id/edit~~ (Solved in https://github.com/Coursemology/coursemology2/commit/60dee8843d3a47120aef8f4e0139243c56bfe99e)

**Course Announcements Page (courses/:courseId/announcements):**
- [x] ~~Backend pagination instead of frontend~~ (Page query is not expensive and loading speed is quite fast now).
- [x] ~~Quite a few files in the codebase are misnamed as .tsx files (they should be .ts files)~~ (Solved in https://github.com/Coursemology/coursemology2/pull/4839/commits/5cc2d482fa917b8122a1f88bcd38553e1b6278d5)

**Submissions (courses/:courseId/assessments/submissions):**
- [x] Clear filters functionality / button (https://github.com/Coursemology/coursemology2/pull/5015/commits/27280e41a66e239a2be30e00d250461262f499ca)

**Workbin (/courses/:courseId/materials/folders/:folderId):**
- [x] Allow users to unstage files when uploading (https://github.com/Coursemology/coursemology2/pull/4868/commits/582b3bb8f0314b267d90f30ff3898c74674fc73d)

**Others:**
- [x] Issue pointed out by Jon (New announcements dialog) (https://github.com/Coursemology/coursemology2/pull/5015/commits/27280e41a66e239a2be30e00d250461262f499ca)
![image](https://user-images.githubusercontent.com/48171632/182326477-fcf8eaeb-1b53-4ebc-bfda-cda5e4b97287.png)

- [x] Dialogs have a scroll bar sometimes, likely due to ckeditor

**Comment by ekowidianto** [comment]
Updated the list above as those are no longer an issue
