### ISSUE TITLE
Bug: Video's page 'Watch' button links me to wrong page that gives me "Access Denied"

### ISSUE THREAD

**Issue by chrisgzf** [Coursemology/coursemology2#4958]
Note: I'm a Phantom Student in [IT2900 - Technical Management & Leadership (AY2022/2023, Sem1)](https://coursemology.org/courses/2173), not sure if this bug only affects phantom students or everyone else.

# Repro Steps

1. Try to watch a video that is uploaded to a course
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/4933577/184498126-645d67ac-64e3-4b83-ae5d-c6b14c6ed1db.png">

2. "Watch" button links me to https://coursemology.org/courses/2173/videos/12288/submissions (see bottom left of pic above)

3. Clicking on button leads me to a page that says "Access Denied"

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/4933577/184498001-74bd9b1b-7ba4-4ffd-be64-6ed8631e2cec.png">

I then emailed Prof Ben about it and he sent me a link that was working: https://coursemology.org/courses/2173/videos/12288/submissions/296245/edit

This link works, shows me the video and does not give me any "Access denied"

Going back to the previous page with the video listings, the button becomes "Re-watch" and the button links correctly to https://coursemology.org/courses/2173/videos/12288/submissions/296245/edit.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/4933577/184498155-2b4c7956-58dc-43a3-9cf0-cd1f5fde1648.png">

I think there might be some issues with the linking of the "Watch" button.

**Comment by ekowidianto** [comment]
Hi @chrisgzf, thanks for reporting this issue. I was trying to reproduce this issue and by any chance did you click open in new tab for the watch button?

**Comment by chrisgzf** [comment]
@ekowidianto Yeah i did
