### ISSUE TITLE
Comments hyperlink to user links incorrectly references userId instead of courseUserId

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4990]
1. Hyperlinks on names are linking to `user.id` instead of `courseUser.id`

https://coursemology.org/courses/course-id/comments

https://github.com/Coursemology/coursemology2/blob/5cc2d482fa917b8122a1f88bcd38553e1b6278d5/client/app/bundles/course/discussion/topics/components/cards/CommentCard.tsx#L205

2. Seperately, the avatar should be linked as well, users will expect to be able to click on the image to link to user.  
See how leaderboard does this:

https://github.com/Coursemology/coursemology2/blob/6a48de998559ec2a4c42140646747120b5838525/client/app/bundles/course/leaderboard/components/tables/LeaderboardTable.tsx#L137

~~3. For consistency, comments and annotations in the submission page should also be hyperlinked
https://coursemology.org/courses/course-id/assessments/assessment-id/submissions/submission-id/edit~~

**Comment by ekowidianto** [comment]
For number 1, there may be N+1 issue as we need to query the course_users table. To solve this, we could preload the course_users and store it inside a hash. In the jbuilder, we then get the course_user based on the user_id. The correct behaviour is to pass json.isCourseUser as well and render either `getCourseUserURL or getUserURL`.

![image](https://user-images.githubusercontent.com/42570513/186083600-f4717db5-0729-47c8-a688-c59c6ebd2588.png)

Item number 3 is removed as of now.
