### ISSUE TITLE
Edmodo Integration with Coursemology

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#502]
Figure out how to do this. Will try my best to update progress here. 

### Current Tasks
- [ ] Read Edmodo API Guide
- [ ] Figure out the exact use cases for integration - decide on what components need to be integrated
 - [ ] User / Authentication
 - [ ] Course (Coursemology) to Class (Edmodo)
- [ ] Get down to implementing them in Coursemology
- [ ] Test this in Edmodo's Sandbox

cc: @lowjoel

**Comment by lowjoel** [comment]
Thanks, I'm not sure how Edmodo and Coursemology's functionality can integrate though.

**Comment by weiqingtoh** [comment]
I'm going to close this for now, will skip integration with Edmodo.
