### ISSUE TITLE
React Pages Migration (Phase 2)

### ISSUE THREAD

**Issue by ekowidianto** [Coursemology/coursemology2#5098]
- [x] Course settings
- [x] Conditions
- [x] Account settings
- [x] Course assessment
- [x] Course video
- [x] Course forum

**Comment by purfectliterature** [comment]
## Assessments
- [ ] `/assessments`
- [ ] `/assessments/:id`
- [ ] `/assessments/:id/question/multiple_responses/new`
- [ ] `/assessments/:id/question/multiple_responses/new?multiple_choice=true`
- [ ] `/assessments/:id/question/voice_responses/new`
- [ ] `/assessments/:id/question/text_responses/new`
- [ ] `/assessments/:id/question/text_responses/new?file_upload=true`
- [ ] `/assessments/:id/question/forum_post_responses/new`

**Comment by ekowidianto** [comment]
@purfectliterature Added more TODOs
