### ISSUE TITLE
Grade multiplier on mobile browser

### ISSUE THREAD

**Issue by markusyeo** [Coursemology/coursemology2#5111]
On my mobile browser, I am unable to type in "." in the multiplier section for late submissions, however it is possible when typing from the laptop or pasting the value in of example "0.8"

![5DDDBFEC-963F-4077-8BB4-AFE5AFF7AE83_1_201_a](https://user-images.githubusercontent.com/62845336/190840810-bf5f96cd-dcfc-481a-bee5-afae3ee1c029.jpeg)

Running Safari on IOS 16.0,

**Comment by ekowidianto** [comment]
Seems like it’s ios/safari 16 issue only as this issue cant be replicated in earlier versions. We will wait and see if it will be fixed soon.
