### ISSUE TITLE
Allow to change the host and name of the instance

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#596]
Currently we can only add/delete instance.

One question is: __Can instance admins change the hosts of their own instances ?__
The dangerous part is that if they changed wrongly, they will never be able to access the instance unless global admin fix for them.  so I lean to not allowing this.

### Task
- [ ] Support edit instance for global admin
- [ ] Defining abilities

**Comment by lowjoel** [comment]
They should not be able to. Manipulating instances is something only global 
admins can do.

**Comment by allenwq** [comment]
Sure, I agree.

**Comment by allenwq** [comment]
Fixed in #631
