### ISSUE TITLE
Cannot change user's role in course or admin users management

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#602]
Nothing happens when clicking the save button in course users management or admin users management.  Both of them have multiple forms in a single page.

I suspect this is because of turbo links.

**Comment by kxmbrian** [comment]
The buttons work for me. Is this solved? Does it only happen sometimes?

**Comment by allenwq** [comment]
It always happens, can you try switch to another tab and then switch back, see if it works for you ?

**Comment by kxmbrian** [comment]
okay, the bug is there.

**Comment by allenwq** [comment]
@kxmbrian This should be fixed ?

**Comment by kxmbrian** [comment]
Fixed by #1321
