### ISSUE TITLE
Missing default Announcement component title

### ISSUE THREAD

**Issue by xzhflying** [Coursemology/coursemology2#611]
If you set the announcement component title to be default, then the page header of announcement index page will have no title.

**Comment by xzhflying** [comment]
![image](https://cloud.githubusercontent.com/assets/8858295/11358388/3238171c-92ac-11e5-9d20-b76f83dda535.png)

**Comment by xzhflying** [comment]
I've found the problem. It is caused by `format_inline_text`. For now, `format_inline_text(nil)` will return `""` instead of `nil`.

**Comment by lowjoel** [comment]
@xzhflying please open a ticket and assign to yourself to fix the rest of the components, thanks.
