### ISSUE TITLE
Submissions Management

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#614]
We need a page to display and manage all the submissions. User can filter submissions by assessments, tutors or students.

Sample page in v1:

![screen shot](https://cloud.githubusercontent.com/assets/4983239/11386325/60ff0cea-935b-11e5-9f52-6e0c011330d9.png)

### Tasks

- [x] Display all submissions
- [ ] Read/Unread of submissions

**Comment by lowjoel** [comment]
@luoyanjie What are the use cases for this feature?

Would people want to search for all submissions by a tutor, or all the assessments of a student, or...?

**Comment by luoyanjie** [comment]
Well I think Ben was the one who asked for this to be built in V1. 👅 

But anyhow, I suspect it's the following case
1) Trying to track submission of a particular training/submission
2) Check submission status by class/tutor
3) Check student's submission trend

**Comment by lowjoel** [comment]
Somehow I think the raw data isn't too useful. The kinds of questions that this needs to answer should guide how it's implemented. Dumping hundreds of rows isn't terribly useful IMO

**Comment by benleong** [comment]
As boss, I need a way to search for all the work graded by a tutor. Also,
sometimes I need a tutor to cover for other tutors. They will need this
interface to access submissions not from their own students.

Submissions by the students can already be accessed from the students'  EXP
summary.

**Comment by benleong** [comment]
Current interface is probably not the most ideal, but it was cheap to hack
together. You guys can probably do better.

**Comment by weiqingtoh** [comment]
Just transferring some discussions over. 

> @lowjoel: I would have pending gradings show up as a notification and I would never go and see the list of pending gradings, unless I'm covering for another tutor.

> @benleong: Pending gradings should only reflect the gradings for a tutor, unless it's
the lecturer, who sees everything.

> @kxmbrian: For a staff member's landing page, have a dashboard with compulsory item completion overview for each of my students.
> - Perhaps this is more for the TA / Head tutor. This feature helps me with my biggest to-do of getting students through the course.
> - I'm quite happy to use the sidebar to get to the routine items like my pending grading.

**Comment by weiqingtoh** [comment]
After discussion, to combine pending gradings as submissions as a single sidebar item. 

There will be multiple tabs, one for `pending gradings`, and additional tabs for each assessment category.
