### ISSUE TITLE
Support Manually Giving Achievements 

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#618]
### Tasks

- [ ] Give achievements to students 
- [ ] Take away achievements from students

**Comment by weiqingtoh** [comment]
Cannot take away achievements from students, so will just mark that as complete.

**Comment by lowjoel** [comment]
Why not? Some courses need it.

**Comment by weiqingtoh** [comment]
Okay misunderstood this. Will undo it for now.

**Comment by weiqingtoh** [comment]
Fixed by #898
