### ISSUE TITLE
Implement Leaderboard

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#634]
Think we will introduce groups to leaderboard in v2 ?  That means we can see the leaderboard of a group. 

### Tasks

- [x] Rank students by level, and by achievements
- [x] Leaderboard Settings 
- [x] Add group leaderboard settings

**Comment by weiqingtoh** [comment]
Completed, pending small fixes for Course Leaderboard. 

Do we need to do for groups, or no need?

**Comment by lowjoel** [comment]
How is it done in v1?

**Comment by weiqingtoh** [comment]
Comparing to v1, I implemented guilds the other time, which is a leaderboard for a collective group (using average experience points of members in that guild/group). That has not been done in v2 yet; and I can do that next.

**Comment by weiqingtoh** [comment]
Comparing to v1, I implemented guilds the other time.

I suspect guilds are slightly similar to groups now, and what I also did was have a leaderboard for each guild. The leaderboard will rank guilds based on average experience points of members in that guild/group. That has not been done in v2 yet; and I can do that next.

**Comment by lowjoel** [comment]
I think by group is good.

**Comment by weiqingtoh** [comment]
I will need to fix up the leaderboard stuff first, otherwise I should be able to get the group leaderboard based on the existing features.

**Comment by weiqingtoh** [comment]
This issue is completed, to close.
