### ISSUE TITLE
Allow streamy access to attachments

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#662]
Currently CarrierWave only allows us to read an entire file into memory if we want to be backend agnostic. This is not possible for large attachments.

Tagged security because file uploads can be big, and can cause DoS.

**Comment by lowjoel** [comment]
@allenwq can add your findings here.

**Comment by cysjonathan** [comment]
large file is going to blow memory https://github.com/carrierwaveuploader/carrierwave/issues/1780
Fix CarrierWave reads large files into memory https://github.com/carrierwaveuploader/carrierwave/pull/2314
Should be fixed in CarrierWave >= 1.2.3

**Comment by zhuhanming** [comment]
In that case, this should be fixed, as the current version of `carrierwave` is 2.1.0.
