### ISSUE TITLE
Unable to load forum post: Error 500

### ISSUE THREAD

**Issue by Beebeeoii** [Coursemology/coursemology2#6691]
I encounter this issue randomly (it doesn't happen all the time, but it does happen quite regularly). When I try to open a topic in a forum, I get greeted with a toast: "Failed to retrieve forum data". Upon further investigations, seems like there is some internal server errors going on.

What I have to do is to simply refresh the page and most of the times it would work on the second try.

The endpoint responsible is: `GET https://coursemology.org/courses/{courseId}/forums/{forumName}/topics/{topicName}?format=json`

**To reproduce:**
1) Open the forums
2) Click into a topic

## Screenshot
<img width="1440" alt="Screenshot 2023-10-20 at 11 20 53 PM" src="https://github.com/Coursemology/coursemology2/assets/55170539/1cb70f66-91ff-4573-8ebd-ef98e6d143fe">

## System
- Firefox 118.0.2 (64-bit)
- macOS Sonoma 14.0
- M1 Macbook Air 2020

**Comment by heyzec** [comment]
Same! I also am facing this issue regularly and randomly. Might be something related to Firefox, I am using Firefox 118.0.1 (64-bit).

**Comment by cysjonathan** [comment]
Can you clarify if this happens only on forums or generally for any tab (students, leaderboard, assignments, announcements, etc)? This will help us narrow down the issue as we investigate.

**Comment by heyzec** [comment]
For me, I've only ever experienced it on the forums.

**Comment by Beebeeoii** [comment]
This only happens for forums and specifically loading of a particular forum topic
