### ISSUE TITLE
Implement CRUD for Experience Points Records

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#688]
Tasks:
- [x] Create Manual EXP Record
    - [x] Basic EXP Disbursement interface
    - [x] Add filters, e.g. filter own students
    - [x] Add "Copy EXP" feature that fills the same EXP for all selected students
    - [x] Add forum EXP Disbursement interface
- [x] Read EXP Records - Student's EXP History
    - [x] Basic EXP History
    - [x] Make it part of CourseUser Profile (Link added)
    - [x] Properly display each EXP awarding component -- generate display string.
    - [x] Add pagination
    - [x] Add feature to allow user to click on EXP reason and get redirected to the item for that record
- [ ] Update Manual EXP Record -- for now, workaround by deleting then recreating the EXP record
- [x] Deleted Manual EXP Record
- [x] For Assessments, auto-recommend EXP values based on grade.

**Comment by weiqingtoh** [comment]
#945 implements some of this already. @kxmbrian can help update those that are done? Thanks!

**Comment by kxmbrian** [comment]
@weiqingtoh I've updated the task list!

**Comment by weiqingtoh** [comment]
Thanks! @kxmbrian let me know which parts you need help with, and which parts you plan to do?

**Comment by kxmbrian** [comment]
Remaining item have been move to a separate issue:  #1326
