### ISSUE TITLE
Server-side checks for multiple form submissions

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#70]
[Double Submit Protection](https://github.com/herval/double_submit_protection) has a simple way of doing so (we should use metaprogramming to make this transparent, like CSRF protection)

I think disabling buttons with 'please wait' is hacky.

**Comment by ZhangYiJiang** [comment]
It depends on how sensitive your application is. If your goal is to provide a better user experience, disabling the submit button client side is good enough. 

Server side protection only comes into play if you assume your form is sensitive enough for attackers to actively attack the form by making more than one submission at a time. In that case, you should be rate limiting the form (but you should rate limit everything that's public facing anyway). Even so, disabling the button on the client side is still a good idea.

**Comment by benleong** [comment]
Coursemology v2 is v sensitive. We need server side protection. Thank you.

**Comment by ekowidianto** [comment]
Multiple form submissions will be handled in the client side
