### ISSUE TITLE
Ensure that the computation for course levels is not too expensive

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#710]
Referenced from #708

> @weiqingtoh this looks fine currently, I'm just worried that the overall order of magnitude of calculating this might be prohibitively expensive at scale. - @lowjoel 

@lowjoel Felt there was this issue but decided to handle it later on, and I think it warrants a discussion as well. To me, calculating the level number was the expensive bit, and we did talk about the windows functions. I was looking at Postgres [window functions](http://www.postgresql.org/docs/9.2/static/functions-window.html) to fix that - we can use RANK() to get the level number, but since RANK() starts from 1, and Coursemology levels start from 0, just need to deduct 1. 

Was also experimenting on how to add that part to the SQL query, but found a [postgres extensions gem](https://github.com/dockyard/postgres_ext) instead. Maybe I can try this out and see if that might make things faster?

**Comment by benleong** [comment]
We can try a very simple scheme where we have a ranking in the schema.
Every time we add a new EXP, we update all the existing entries using code.
Simple is good hor.

**Comment by lowjoel** [comment]
Simple is better, definitely.

@weiqingtoh how does the gem help with the querying? It only supports CTEs and the CIDR datatype -- is there something else I'm missing?

**Comment by weiqingtoh** [comment]
@lowjoel Instead of manually appending level numbers when we query course levels, we can use the [RANK() window function](https://github.com/dockyard/postgres_ext/search?utf8=%E2%9C%93&q=rank) to do it. With the gem so there is no need to manually chain this into the SQL query. 

The other alternative is to store the level number by adding he another column to the db.

**Comment by lowjoel** [comment]
Ah, okay. Try it out, see how it goes. You can make the rank column read only, and add a model method which takes the generated value and returns one less.
