### ISSUE TITLE
Assignment URL query parameter "step" doesn't open directly to the right step anymore

### ISSUE THREAD

**Issue by pakshuang** [Coursemology/coursemology2#7161]
This used to work in the past, but at some point it stopped working.

I am referring to the `?step=3` query parameter at the end of the URL for a assignment submission.

It's mostly a QoL issue, it is just annoying when a student links a particular step to you or you link a particular step to a group chat of TAs, but it doesn't actually take you to that step.

**Comment by cysjonathan** [comment]
Fixed by #7491
