### ISSUE TITLE
Email cannot be added to account if there is an outstanding invitation

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#735]
User: 
- Signs in with Facebook using an email address fb@example.com. 
- Receives a course invitation to a course at another email address random@example.com.

If invitation is forgotten:
- The password for random@example.com cannot be reset as the reset form will complain that the  email field cannot be blank even after the address is confirmed.

When signed in as fb@example.com and trying to add random@example.com as an alternate email, the error message "Email has already been taken and Email has already been taken" appears. (Yes it repeats twice). This is raised in #736 

There is no clear way in the UI to resolve this "orphaned" email address.

**Comment by allenwq** [comment]
Fixed in #1255
