### ISSUE TITLE
Deactivating Group Leaderboard on Course Settings should immediately disable the Group Leaderboard page

### ISSUE THREAD

**Issue by bivanalhar** [Coursemology/coursemology2#7430]
## Steps to Reproduce

- Activate the Group Leaderboard setting inside the Course Settings by navigating to Course Settings -> Leaderboard -> ticking the "Enable Group Leaderboard" box
- Navigate to the Leaderboard page (/courses/{courseId}/leaderboard)
- Go back to Course Settings -> Leaderboard -> untick the "Enable Group Leaderboard" box
- Then, without refreshing, go back to the Leaderboard page

![Screenshot 2024-07-12 at 5 18 39 PM](https://github.com/user-attachments/assets/8a415959-401a-4626-9814-70413161fbfb)

The tab of "Group Leaderboard" (or whatever is the name, based on the title that's being set inside the Course Settings) will still be there.

![Screenshot 2024-07-12 at 5 19 39 PM](https://github.com/user-attachments/assets/53a8e161-afc3-4eb7-9fc8-8dfcd3f62570)

## Possible Cause

Most probably it's because the value to be shown for group leaderboard is based on what's stored inside the Redux, and those values did not get reset when the settings are disabled or when we go to the Leaderboard page.
The page is displayed correctly when we refresh the page, though.

## Expected

After we disable the Group Leaderboard, we should not see the Group Leaderboard tab anymore when we navigate to the Leaderboard page

**Comment by cysjonathan** [comment]
Closed by #7500
