### ISSUE TITLE
Forum Question is still marked as Resolved even when all the "Marked as Answer" posts are deleted

### ISSUE THREAD

**Issue by bivanalhar** [Coursemology/coursemology2#7439]
## How to Reproduce

- Go to the existing Forum and Topic that is classified as question (if there does not exist, create one such topic)
- Mark some of the answers (not all) as answer by clicking the button "Mark as Answer" on the bottom of each of their posts
- Then delete all those answers

By right, since none of the posts are marked as answer now, the question should be "still unresolved". Instead, the state of the question being "already resolved" still holds, as shown below

<img width="1513" alt="Screenshot 2024-07-17 at 11 46 41 AM" src="https://github.com/user-attachments/assets/d57b67bd-5de3-46d1-a319-72ba8dff1f2a">

## Expected Behavior
When the last "marked as answer" post got deleted, the question's state should change to "still unresolved"

**Comment by cysjonathan** [comment]
Closed by #7501
