### ISSUE TITLE
"Hide" and "Lock" button in Forum Topic page is not intuitive

### ISSUE THREAD

**Issue by bivanalhar** [Coursemology/coursemology2#7440]
When user goes into one of the Forum Topic page (/courses/{courseId}/forums/{forumName}/topics/{topicName}), there are buttons called "Hide" and "Lock" on the upper right of the page. Those two are not intuitive enough for user, as to what it actually means

It's better to have the toggle message (just like Unsubscribe button, also located side-by-side with Hide button) that explains what the button will do.

- Hide -> Students will not be able to see this topic
- Lock -> Students will not be able to add reply or post in this topic

**Comment by cysjonathan** [comment]
Closed by #7501
