### ISSUE TITLE
Deleting or Adding Level into Level Page should have its UX changed

### ISSUE THREAD

**Issue by bivanalhar** [Coursemology/coursemology2#7442]
## Background

<img width="1513" alt="Screenshot 2024-07-17 at 1 41 18 PM" src="https://github.com/user-attachments/assets/841ecaf2-5fec-45b0-8c76-f2d64abb2351">

Currently, if user wants to add more levels into the course, all those new levels will appear as like the other, already existing, levels. This might confuse user as to they might forget which level entity they have saved and which ones they have not yet committed.

Another thing also is that should user inadvertently delete a level entity, that level will disappear from the page but is actually still existing inside our DB until user click on "Save Level". There's no way for user to get back that "accidentally" deleted level except for them to refresh the page, which might be annoying if user also have other added entity that hasn't been saved yet (and even might lead to user needing to repeat the process again)

## Fix Suggestion

- We might apply the similar behavior as was questions, in which when user attempted to add levels, those new entities will have green background to differentiate it from the rest. Also when user attempted to delete some levels, those selected entities will have red background and the button "Delete" will be changed to "Undo", to ensure that any mistake in user's action can be reverted
- Should there be any levels user attempts to delete, when saving, user should be warned that some of the levels are about to be deleted (will be better if the warning also identifies which levels are to be deleted)

**Comment by syoopie** [comment]
Page refactored and lifted in #7540
