### ISSUE TITLE
Assessment cannot be deleted if at least one user has attempted it

### ISSUE THREAD

**Issue by evansb** [Coursemology/coursemology2#759]
To reproduce

1. Create an assessment
2. Attempt it
3. Try deleting the assessment

**Comment by allenwq** [comment]
This should be fixed after course is deletable:

but I get another exception while deleting the assessment: 
``PG::ForeignKeyViolation: ERROR: update or delete on table "course_assessments" violates foreign key constraint "fk_course_condition_assessments_assessment_id" on table "course_condition_assessments" DETAIL: Key (id)=(1) is still referenced from table "course_condition_assessments". : DELETE FROM "course_assessments" WHERE "course_assessments"."id" = $1```

**Comment by allenwq** [comment]
Fixed in #1118
