### ISSUE TITLE
Making attachments immutable stores

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#779]
The current has_one_attachment and has_many_attachment directly modifies attachment records. That means if they are changed then the S3 file will be left, but the table record will have changed.

Change the framework to not allow modifications to attachments.

Also, maybe we need to find a way to do refcounting for the attachments on the remote store. Currently each attachment can only have one owner. Duplicating courses will change this.

**Comment by lowjoel** [comment]
Also, I think `dependent: :destroy` would also allow attachment references to S3 to be lost.

**Comment by allenwq** [comment]
@lowjoel Attachment itself can be used as a counter ? Duplicating course will duplicate the attachment and the new attachment points to the same carrier wave file on S3.

**Comment by lowjoel** [comment]
It's not as easy to know then which files on S3 are no longer being used.

**Comment by allenwq** [comment]
Actually why we want to know which files are not be used ? 

And in that case we can implement in a way such that attachment don't get deleted when it's the last one (only set owner to nil).

**Comment by lowjoel** [comment]
There is no way to determine if an attachment is the last reference to a file in a thread safe manner based on the current implementation

**Comment by allenwq** [comment]
Yes. and again why we want to track deleted files on s3 ?

**Comment by lowjoel** [comment]
Because then we’ll be paying for space that no one uses?


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by allenwq** [comment]
The files on s3 are deleted after attachments were changed or destroyed now, so it would not be an issue ?

**Comment by lowjoel** [comment]
Then that's a problem -- if you say after duplicating a course you'll have two attachments, then the other attachment will be referencing a missing file

**Comment by allenwq** [comment]
I thought amazon files won't be deleted before.

Yah, I think making attachment immutable makes sense in this case. We can further add a file hash column in the attachment table and don't upload duplicated files to S3.

**Comment by lowjoel** [comment]
Fixed in #880
