### ISSUE TITLE
Multiple achievement conditions loaded at achievement listing page

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#804]
<img width="1580" alt="screen shot 2016-02-15 at 9 14 01 am" src="https://cloud.githubusercontent.com/assets/4353853/13037845/8ddd374c-d3c4-11e5-9c65-e07bb585f369.png">

**Comment by weiqingtoh** [comment]
Still trying to figure out the problem. Noted findings: 
 - The removal of this [line](https://github.com/Coursemology/coursemology2/blob/master/app/controllers/course/achievements_controller.rb#L6) (which eager loads `conditions` on each achievement) solves the problem.
 - Issue only happens for Admins, and students do not see duplicates (tested on staging)

**Comment by weiqingtoh** [comment]
@allenwq helped to debug - SQL query is below. 

Root cause is probably `cancancan`, which triggers this `FROM` statement. This causes the duplicated conditions. Doesn't happen for course students because not all `course_users` are selected for non-admins. 

```SQL
FROM
		"course_achievements" LEFT OUTER JOIN "courses"
			ON "courses" . "id" = "course_achievements" . "course_id"
		AND "courses" . "instance_id" = 1 LEFT OUTER JOIN "course_users"
			ON "course_users" . "course_id" = "courses" . "id" LEFT OUTER JOIN "course_conditions"
			ON "course_conditions" . "conditional_id" = "course_achievements" . "id"
		AND "course_conditions" . "conditional_type" = "Course::Achievement"
```

[Full Query here](https://gist.github.com/weiqingtoh/515da1a4808f44971c85)

**Comment by weiqingtoh** [comment]
This was solved by #952; the repeat conditions stopped appearing since then. Shall I close this?

**Comment by lowjoel** [comment]
yup :)

**Comment by weiqingtoh** [comment]
Swee
