### ISSUE TITLE
Only registration code text field and button when necessary

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#805]
Currently I think the registration text-field and button is always shown at the course homepage. The page should not show this unless:
 - user has not registered for course
 - course allows registration through a certain code.

**Comment by lowjoel** [comment]
Can't wait for course codes only because email invitations also use codes.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by weiqingtoh** [comment]
Oh is that the reason why that bar is there? Then maybe can close this issue.

**Comment by lowjoel** [comment]
I think it can still check if the user has not registered for a course. Registered users shouldn't need a registration code.
