### ISSUE TITLE
can? always returns true when checked against classes

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#813]
Our cancancan abilities are typically defined using hashes.

From the [cancancan wiki](https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities):
> **Important**: If a block or hash of conditions exist they will be ignored when checking on a class, and it will return `true`. 

One visible example:
- Log in as a normal user (w/o permissions to create courses) and navigate to the course listing
- You will find the "new course" button, but clicking on it will lead you to the access denied page.

**Comment by fonglh** [comment]
Fixed by #812
