### ISSUE TITLE
Implement a todo list

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#867]
This can be built on top of the lesson plan information

**Comment by allenwq** [comment]
In v1 only pending assessments are displayed, and there is a link to assessment#show and button to assessment#attempt, shall we do that as well ?

**Comment by allenwq** [comment]
@lowjoel @weiqingtoh @fonglh @kxmbrian  Any concerns ?

**Comment by lowjoel** [comment]
I was thinking of generalising this to things on the lesson plan that needs to be done. So the lesson plan items can implement some kind of "incomplete" scope for the main page to figure out what needs to be done.

**Comment by allenwq** [comment]
Then the question is what should be considered as "incomplete", does it adopt to all types of lesson plan items ? 

This actually similar to read/unread to me, user can ignore a todo item just as mark things as read.

**Comment by weiqingtoh** [comment]
Actually there is another aspect, from the staff perspective (pending grading), on top of students (pending tasks). It might be good to consider surveys also.

I suspect read/unread is more for notifications, the todo list should still show the assessment/survey unless it is finished. Because these are more critical things that teachers/lecturers require for students to complete.

**Comment by allenwq** [comment]
I think pending gradings should be implemented separately ? I'd rather using a grading page for that.

Yes, but I mean the design is similar to read/unread, not using it. Students can mark items as ignored even they haven't finish it.

**Comment by lowjoel** [comment]
I would have pending gradings show up as a notification and I would never go and see the list of pending gradings, unless I'm covering for another tutor.

I agree with @weiqingtoh that the todo list should be generic, and that it should not be dismissable.

**Comment by benleong** [comment]
Pending gradings should only reflect the gradings for a tutor, unless it's
the lecturer, who sees everything.

**Comment by allenwq** [comment]
@lowjoel @weiqingtoh I suspect in v1 student can ignore the pending item is because there are lots of optional assessments. We should not make them dismissible in that case ?

**Comment by kxmbrian** [comment]
After my experience with v1, there are the different "to-do's" and use cases that I suggest:

1. Have a list of un-dismissable compulsory items on the landing page for students.
  - This feature helps tutors to chase students to finish their assignments/surveys.
  - Perhaps have the option under lesson plan item to mark things as "compulsory"
1. Unread bubbles -- "to-see list"
  - As a student, this is good for me to know stuff exists, e.g. new file uploaded, new training. I don't always want to or have to do anything about them. Email notifications may serve this purpose, but they can be noisy and seeing them in the sidebar gives me a nice overview.
  - As a tutor, it serves as my to-do list. I need to grade all assignments, clear all comments/forum posts etc. Clear all the routine work == clear all bubbles.
1. Put checks/ticks for completed items in Lesson Plan. Be able to filter items that are not yet completed.
  - As a student, good for me to find extra practices. Or aim for OCD badge.
1. For a staff member's landing page, have a dashboard with compulsory item completion overview for each of my students.
  - Perhaps this is more for the TA / Head tutor. This feature helps me with my biggest to-do of getting students through the course.
  - I'm quite happy to use the sidebar to get to the routine items like my pending grading.

**Comment by weiqingtoh** [comment]
We can take pending gradings into a separate discussion -> #614, I'll copy the relevant comments there. 

Actually @allenwq has a good point that there are optional assessments/items in certain courses. Given this, I'm actually in favour of having a dismissible to-do list acting as notifications; and lesson plan as a non-dismissible list.

Also, we will probably need to have an optional field for each `lesson_plan_item`.

**Comment by weiqingtoh** [comment]
Todo list for todo list:
- [ ] Define todo model and APIs
- [ ] Implement hooks on `lesson_plan_item` and `course_user`
- [ ] Implement todo status (probably as enum) on todo model
- [ ] Implement hooks into `assessment` and `submissions`
- [ ] Rake task to populate all todos for students
- [ ] Implement controller (to ignore) for todos
- [ ] Implement views for todo - general page view and appearance of assessment todos.

**Comment by weiqingtoh** [comment]
Completed
