### ISSUE TITLE
Display helpers for course user profile

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#873]
For the course user badge and discussion authors

**Comment by weiqingtoh** [comment]
Do you mean having something like `display_course_user_profile` which renders HTML showing the `course_user_profile_picture` and `course_user_name`?

**Comment by lowjoel** [comment]
I think this is more accurately described as making display_course_user and link_to_course_user a bit more useful, like so we can use these functions in forums and discussions to show the user's profile pic etc.

**Comment by ekowidianto** [comment]
Page ported to react
