### ISSUE TITLE
Allow assessments to decide whether to automatically release grades

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#876]
Useful for assisted grading.

**Comment by weiqingtoh** [comment]
After discussion, it will be best to implement this with a boolean flag `automatically_release_grades` at the assessment level. Tasks include:

- [ ] Adding option in assessment (and validations)
- [ ] Modifying the logic for guided mode to handle `true` and `false` values of `automatically_release_grades`

The discussion point will be how to handle guided mode:
- If `automatically_release_grades` is `true`
 - Currently implemented in a sequential format (I must complete qn 1 before I go on to qn 2).
 - At some point we might want to allow a non-sequential method? (Means student can do qn 3 before qn 1 and 2).
- If `automatically_release_grades` is `false`
 - Sequential format: proceed to qn 2 only if an answer is provided for qn 1.
 - Non-sequential format: similar to above when `true`.

What do you guys think? 
@lowjoel @allenwq @kxmbrian @fonglh

**Comment by lowjoel** [comment]
What were the reasons for individual questions having this flag, are they still relevant?

**Comment by weiqingtoh** [comment]
Just copied the docs and code here for reference. I suspect this flag was to help the submissions controller know whether or not to invoke an autograder service once an answer is submitted for a particular question.

If you ask me, the flag is still relevant but should not be configured by user - whether or not the question is auto_gradable depends on whether the question satisfies certain conditions, which should be left up to the specific question to implement. 

```ruby
  # Checks if the given question is auto gradable. This defaults to false if the specific
  # question does not implement auto grading. If this returns true, +auto_grader+ is guaranteed
  # to return a valid grader service.
  #
  # Different instances of a question can have different auto gradability.
  #
  # @return [Boolean] True if the question supports auto grading.
  def auto_gradable?
    actable.present? && actable.self_respond_to?(:auto_gradable?) ? actable.auto_gradable? : false
  end
```
