### ISSUE TITLE
Saving new comment after deleting last comment triggers error

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#891]
Opening a submission, deleting the latest comment, then saving the submission, will generate an error.

Probably because the parent post as submitted in the form no longer exists.

**Comment by weiqingtoh** [comment]
Should be fixed if by @kxmbrian - to disable deletion of posts.

**Comment by allenwq** [comment]
@kxmbrian Has this been fixed ?

**Comment by kxmbrian** [comment]
Not yet

**Comment by kxmbrian** [comment]
Fixed by #1903
