### ISSUE TITLE
An SMTP To address is required to send a message when registering for a course

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#918]
I hypothesise it's because there are course staff who do not have an email.

Or there are courses without any course staff.

**Comment by lowjoel** [comment]
Rollbar #67

**Comment by allenwq** [comment]
@fonglh This seems to be fixed ?

**Comment by fonglh** [comment]
By #1283?

**Comment by allenwq** [comment]
No, this is relate to configuration ?

**Comment by fonglh** [comment]
No, it's either bad data like Joel suggested, or code that doesn't check for an email address. I think it's fixed with user registration.
