### ISSUE TITLE
link_to_user should not create links to unconfirmed users

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#920]
Also, when requesting the profile for an unconfirmed user, it should return a 404.

See Rollbar 76.

**Comment by allenwq** [comment]
I think we should filtered out the unconfirmed users in the controller first ? then maybe raise a exception in link_to_user when user is not confirmed.

**Comment by lowjoel** [comment]
Cannot raise an exception in link_to_user. The user might be disabled, for example. That will break a lot of pages.

**Comment by allenwq** [comment]
that's why we need to filter out the unconfirmed users first, in the course user index page we should only display user with approved state ?

**Comment by lowjoel** [comment]
It's not only in the course user index page that link_to_user is used.

**Comment by allenwq** [comment]
any other places that we want to display a unconfirmed user ?

**Comment by lowjoel** [comment]
achievements listing page, all places with a discussion. it's all over the place, a grep will show...

**Comment by allenwq** [comment]
why achievement listing and discussion page will list unconfirmed user ? I think all of them need to be scoped to approved first.

**Comment by lowjoel** [comment]
all pages with a discussion will store a reference to a user in the system. think about what happens when you have an admin or something who does not belong in the course, or an admin who is waiting for a course role approval.

discussions will still display them anyway. the discussion post doesn't disappear because the guy was an admin when posting, and disappears when he's waiting for a course user role approval?

**Comment by allenwq** [comment]
I think the exception was because that the course_user references a nil user. For those cases the helper will still work ?

**Comment by lowjoel** [comment]
sure, there's a name already even if there's no user. that's why there needs to be extra logic within the helper.

**Comment by allenwq** [comment]
OK, the helper need to be modified, and the unconfirmed course_users in the index page need to be filtered too.

**Comment by weiqingtoh** [comment]
Arising for this discussion, I suppose there are a few tasks: 

- [ ] Filter out unconfirmed users from the achievement listing page, and course user index page
- [ ] Add logic to `link_to_user` to not have a link if user is unconfirmed
- [ ] Modify controller to show 404 if user is unconfirmed

Did I get this right?

**Comment by lowjoel** [comment]
sounds about right.

**Comment by weiqingtoh** [comment]
All tasks completed.
