### ISSUE TITLE
Only show course owners at course homepage

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#933]
Currently all the teaching staffs are showed in course homepage.

Think we should only display owners, or maybe owners + managers ?

**Comment by lowjoel** [comment]
What's the v1 behaviour?

**Comment by allenwq** [comment]
V1 only shows `lecturer`, and there is no `manager` in V1.

**Comment by lowjoel** [comment]
I think owners and manager seems good.

**Comment by lowjoel** [comment]
Fixed in #936
