### ISSUE TITLE
Implement Instance admin

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#948]
After #934 is merged, ActsAsTenant allows unscoping out of tenants.

The instance administration pages should allow access to the instance involved.

**Comment by allenwq** [comment]
@lowjoel I further thought about this, this actually does not affect the instance management. because the instance management is done in specific instance. Or you are meaning something else ?

**Comment by lowjoel** [comment]
Yes, at least link to those instances.

**Comment by allenwq** [comment]
OK, will handle the links between instances after #988
