### ISSUE TITLE
Decide on which components can be disabled

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#950]
For courses, we should probably think about which components can be disabled, and which components can't, and implement that on the UI. Issue arising from #942.

**Comment by weiqingtoh** [comment]
Arising from an email, it was suggested that we can think about whether some of the components can be disallowed at an instance level.

**Comment by allenwq** [comment]
You can, it uses the same set of components as course.

**Comment by lowjoel** [comment]
Disabling a component at the instance level already prevents activation on the course.

**Comment by allenwq** [comment]
We should hide those components which we don't want to disable.

**Comment by weiqingtoh** [comment]
After discussion,

Components that can be disabled:
- Achievements
- Announcements
- Assessments
- Forums
- Groups
- Leaderboard
- Lesson Plan
- Levels
- Materials

Components that **CANNOT** be disabled:
- Courses
- Users

(Points disbursement component to be shifted into course component)
