### ISSUE TITLE
Instructors should be able to comment on questions for instructors to see

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#982]
Instructors should be able to comment on each question they create for their own review and for other instructors to see. This will allow instructors to store the rationale of their question design and answers to their question.

The purpose of storing these comments in context of the question is for the instructor's own review in the future, and for fellow instructors to understand the question better. Also, when the question is duplicated to other courses, other instructors can read the comments to understand the intention of instructor who designed the question. 

**Possible naming of this feature**
- Instructors-only comments
- Question rationale
- Note to other instructors

@lowjoel

**Comment by allenwq** [comment]
I would prefer to name the column `staff_only_comment`, @luoyanjie @lowjoel  what you think ?

**Comment by luoyanjie** [comment]
I have no preference as to how it should be named in the backend. The naming suggestion is more for UI. :D

**Comment by lowjoel** [comment]
What are the terms we use now?
 - Student
 - Owner [1]
 - Manager [1]
 - Teaching Assistant [1]

[1] all instructors?

@luoyanjie The backend naming should reflect the UI naming so new programmers can figure out what's going on.

**Comment by allenwq** [comment]
@lowjoel  TAs are considered as instructors too ?  then `instructors_only_comment` ?

**Comment by luoyanjie** [comment]
When people request for more rights to create courses, in V1, it's called "Get Lecturer access". In v2?

**Comment by lowjoel** [comment]
Which is why we need to settle this here and now... I thought we had an earlier ticket?

**Comment by luoyanjie** [comment]
Ok. Then it will be `Get Teacher access`.
Then this can be `Teaching-team only comments` or `For teaching-team`

**Comment by allenwq** [comment]
@lowjoel I remember an earlier ticket about roles, but we didn't discuss "role group" there: https://github.com/Coursemology/coursemology2/issues/290

**Comment by lowjoel** [comment]
I thought we were to standardise it to instructor access? Instructors can create new courses, that's about it.

**Comment by allenwq** [comment]
So finally we stick the name to `teaching_team_only_comments` ?

**Comment by weiqingtoh** [comment]
How about `staff_comments` or `staff_only_comments`?

**Comment by allenwq** [comment]
@lowjoel @luoyanjie `staff_only_comments` also sounds good to me, any comments ?

**Comment by luoyanjie** [comment]
No pref!
